/**
 * Achievement seed data — all 19 achievements for Raccoon City RPG.
 * These are loaded into the game_achievements table via /api/admin/seed-achievements.
 */

export interface SeedAchievement {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: 'combat' | 'exploration' | 'collection' | 'story' | 'special';
  condition: string;
  hidden?: boolean;
  reward: string;
  sortOrder: number;
}

export const SEED_ACHIEVEMENTS: SeedAchievement[] = [
  // ── COMBAT ──
  {
    id: 'first_blood',
    name: 'Primo Sangue',
    description: 'Sconfiggi il tuo primo nemico.',
    icon: '⚔️',
    category: 'combat',
    condition: 'first_kill',
    reward: 'Coraggio: +5',
    sortOrder: 0,
  },
  {
    id: 'centurion',
    name: 'Centurione',
    description: 'Sconfiggi 100 nemici in totale.',
    icon: '💀',
    category: 'combat',
    condition: 'kill_100',
    reward: 'Esp: +50',
    sortOrder: 1,
  },
  {
    id: 'boss_slayer',
    name: 'Cacciatore di Boss',
    description: 'Sconfiggi il T-103 Tyrant.',
    icon: '👹',
    category: 'combat',
    condition: 'defeat_tyrant',
    reward: 'Onore eterno',
    sortOrder: 2,
  },
  {
    id: 'nemesis_defeated',
    name: 'S.T.A.R.S...',
    description: 'Sconfiggi il NEMESIS durante un\'invasione.',
    icon: '💀',
    category: 'combat',
    condition: 'defeat_nemesis_invasion',
    hidden: true,
    reward: 'Sopravvivenza suprema',
    sortOrder: 3,
  },
  {
    id: 'perfect_combat',
    name: 'Combattimento Perfetto',
    description: 'Vinci un combattimento senza subire danni.',
    icon: '✨',
    category: 'combat',
    condition: 'no_damage_victory',
    reward: 'Prestigio',
    sortOrder: 4,
  },
  {
    id: 'level_10',
    name: 'Veterano',
    description: 'Porta un personaggio al livello 10.',
    icon: '⭐',
    category: 'combat',
    condition: 'reach_level_10',
    reward: 'Forza: +3',
    sortOrder: 5,
  },

  // ── EXPLORATION ──
  {
    id: 'explorer',
    name: 'Esploratore',
    description: 'Visita tutte le 6 location del gioco.',
    icon: '🗺️',
    category: 'exploration',
    condition: 'visit_all_locations',
    reward: 'Conoscenza: +10',
    sortOrder: 10,
  },
  {
    id: 'survivor_50_turns',
    name: 'Sopravvissuto',
    description: 'Sopravvivi per 50 turni.',
    icon: '🕐',
    category: 'exploration',
    condition: 'survive_50_turns',
    reward: 'Resilienza',
    sortOrder: 11,
  },
  {
    id: 'speedrunner',
    name: 'Speedrunner',
    description: 'Completa il gioco in meno di 60 turni.',
    icon: '⚡',
    category: 'exploration',
    condition: 'victory_under_60_turns',
    reward: 'Velocità: +10',
    sortOrder: 12,
  },
  {
    id: 'all_keys_found',
    name: 'Maestro delle Chiavi',
    description: 'Trova tutte e 3 le chiavi in una singola run.',
    icon: '🔑',
    category: 'exploration',
    condition: 'find_all_keys',
    reward: 'Accesso totale',
    sortOrder: 13,
  },

  // ── COLLECTION ──
  {
    id: 'ribbon_1',
    name: 'Primo Nastro',
    description: 'Trova il tuo primo Nastro d\'Inchiostro.',
    icon: '🎀',
    category: 'collection',
    condition: 'collect_ribbon_1',
    reward: 'Memoria salvata',
    sortOrder: 20,
  },
  {
    id: 'ribbon_5',
    name: 'Collezionista',
    description: 'Raccogli 5 Nastri d\'Inchiostro in una run.',
    icon: '🎀',
    category: 'collection',
    condition: 'collect_ribbon_5',
    reward: 'Nostalgia',
    sortOrder: 21,
  },
  {
    id: 'ribbon_all',
    name: 'Compleatista',
    description: 'Raccogli tutti e 10 i Nastri d\'Inchiostro.',
    icon: '🎀',
    category: 'collection',
    condition: 'collect_all_ribbons',
    hidden: true,
    reward: 'Perfezione assoluta',
    sortOrder: 22,
  },
  {
    id: 'bestiary_5',
    name: 'Osservatore',
    description: 'Incontra 5 tipi diversi di nemici.',
    icon: '📖',
    category: 'collection',
    condition: 'bestiary_5',
    reward: 'Saggezza',
    sortOrder: 23,
  },
  {
    id: 'bestiary_all',
    name: 'Enciclopedia Vivente',
    description: 'Sconfiggi tutti i 13 tipi di nemici.',
    icon: '📚',
    category: 'collection',
    condition: 'bestiary_all',
    hidden: true,
    reward: 'Conoscenza totale',
    sortOrder: 24,
  },

  // ── STORY ──
  {
    id: 'savior',
    name: 'Salvatore',
    description: 'Scegli di aiutare i sopravvissuti nel primo evento.',
    icon: '❤️',
    category: 'story',
    condition: 'help_survivors',
    reward: 'Bontà',
    sortOrder: 30,
  },
  {
    id: 'victory',
    name: 'Fuga da Raccoon City',
    description: 'Completa il gioco e scappa dalla città.',
    icon: '🏆',
    category: 'story',
    condition: 'game_victory',
    reward: 'VITTORIA!',
    sortOrder: 31,
  },

  // ── SPECIAL ──
  {
    id: 'herb_master',
    name: 'Erborista',
    description: 'Combina 3 erbe verdi con erbe rosse.',
    icon: '🌿',
    category: 'special',
    condition: 'combine_herbs_3',
    reward: 'Cura naturale',
    sortOrder: 40,
  },
  {
    id: 'auto_combat_win',
    name: 'Comando Automatico',
    description: 'Vinci un combattimento usando solo il combattimento automatico.',
    icon: '🤖',
    category: 'special',
    condition: 'auto_combat_victory',
    reward: 'Strategia passiva',
    sortOrder: 41,
  },
  // ── CRAFTING ACHIEVEMENTS ──
  {
    id: 'master_crafter',
    name: 'Maestro Artigiano',
    description: 'Crea 20 oggetti in totale tramite crafting.',
    icon: '🔨',
    category: 'special',
    condition: 'craft_20_items',
    reward: 'Creatività illimitata',
    sortOrder: 53,
  },
  {
    id: 'quality_crafter',
    name: 'Artigiano Perfetto',
    description: 'Crea 3 oggetti di Qualità Maestra.',
    icon: '⭐',
    category: 'special',
    condition: 'craft_3_master_quality',
    hidden: true,
    reward: 'Perfezione artigianale',
    sortOrder: 54,
  },
  // ── CHAIN SURVIVOR ──
  {
    id: 'chain_survivor',
    name: 'Sopravvissuto alla Catena',
    description: 'Sopravvivi a un evento a catena.',
    icon: '⛓️',
    category: 'exploration',
    condition: 'survive_chain_event',
    reward: 'Resilienza estrema',
    sortOrder: 14,
  },
  // ── NG+ ACHIEVEMENTS ──
  {
    id: 'ach_ng_plus_1',
    name: 'Nuovo Inizio',
    description: 'Completa il primo New Game+.',
    icon: '🎀',
    category: 'special',
    condition: 'ng_plus_1',
    reward: 'La sfida continua...',
    sortOrder: 55,
  },
  {
    id: 'ach_ng_plus_3',
    name: 'Veterano',
    description: 'Completa 3 New Game+.',
    icon: '🏅',
    category: 'special',
    condition: 'ng_plus_3',
    reward: 'Forza indomabile',
    sortOrder: 56,
  },
  {
    id: 'ach_ng_plus_5',
    name: 'Leggenda',
    description: 'Completa 5 New Game+.',
    icon: '👑',
    category: 'special',
    condition: 'ng_plus_5',
    hidden: true,
    reward: 'Leggenda di Raccoon City',
    sortOrder: 57,
  },
];
