import { CharacterArchetype } from '@/game/types';

let uid = 0;
const genUid = () => `item_${++uid}_${Date.now()}`;

export const SEED_CHARACTERS: CharacterArchetype[] = [
  {
    id: 'tank',
    name: 'Tank',
    displayName: 'Viktor Stahl',
    description: 'Combattente corazzato specializzato nell\'assorbimento danni e nella protezione dei compagni. Robusto e resiliente.',
    maxHp: 150,
    atk: 18,
    def: 14,
    spd: 6,
    specialName: 'Barricata',
    specialDescription: 'Solleva una barricata improvvisata, riducendo drasticamente i danni subiti per il prossimo turno.',
    specialCost: 15,
    special2Name: 'Immolazione',
    special2Description: 'Si espone per attirare tutti gli attacchi nemici su di sé, proteggendo gli alleati.',
    special2Cost: 10,
    passiveDescription: 'Resistenza: Riduce i danni subiti del 10% in modo passivo.',
    portraitEmoji: '🛡️',
    startingItems: [
      {
        uid: genUid(), itemId: 'pipe', name: 'Tubo di Piombo', description: 'Un pesante tubo di piombo, affidabile come mazza.',
        type: 'weapon', rarity: 'common', icon: '🔧', usable: false, equippable: true, quantity: 1,
        weaponStats: { itemId: 'pipe', name: 'Tubo di Piombo', type: 'melee', modSlots: [], effects: [{ type: 'buff_stat', trigger: 'on_equip', target: 'self', stat: 'atk', amount: 5, flat: true }] },
      },
      {
        uid: genUid(), itemId: 'bandage', name: 'Benda', description: 'Una benda per fermare le emorragie. Ripristina 25 HP.',
        type: 'healing', rarity: 'common', icon: '🩹', usable: true, equippable: false, quantity: 2,
        effect: { type: 'heal', value: 25, target: 'self' },
      },
      {
        uid: genUid(), itemId: 'flashlight', name: 'Torcia', description: 'Una torcia che può accecare temporaneamente un nemico.',
        type: 'utility', rarity: 'common', icon: '🔦', usable: true, equippable: false, quantity: 1,
      },
    ],
  },
  {
    id: 'healer',
    name: 'Medico',
    displayName: 'Maren Voss',
    description: 'Specialista in cure e supporto medico. Le sue conoscenze mediche sono fondamentali per la sopravvivenza del gruppo.',
    maxHp: 90,
    atk: 10,
    def: 8,
    spd: 8,
    specialName: 'Pronto Soccorso',
    specialDescription: 'Un intervento medico rapido che cura un alleato di una quantità significativa di HP.',
    specialCost: 20,
    special2Name: 'Cura Gruppo',
    special2Description: 'Un intervento medico che distribuisbe cure a tutto il gruppo, curando ogni alleato di una quantità moderata di HP.',
    special2Cost: 25,
    passiveDescription: 'Ippocrate: Le cure hanno un 20% di probabilità in più di essere efficaci.',
    portraitEmoji: '💊',
    startingItems: [
      {
        uid: genUid(), itemId: 'scalpel', name: 'Bisturi', description: 'Un bisturi da chirurgo, affilato ma leggero.',
        type: 'weapon', rarity: 'common', icon: '🔪', usable: false, equippable: true, quantity: 1,
        weaponStats: { itemId: 'scalpel', name: 'Bisturi', type: 'melee', modSlots: [], effects: [{ type: 'buff_stat', trigger: 'on_equip', target: 'self', stat: 'atk', amount: 6, flat: true }] },
      },
      {
        uid: genUid(), itemId: 'first_aid', name: 'Kit di Pronto Soccorso', description: 'Un kit medico completo. Ripristina tutti gli HP e cura veleno/sanguinamento a un alleato.',
        type: 'healing', rarity: 'uncommon', icon: '✚️', usable: true, equippable: false, quantity: 2,
        effect: { type: 'heal_full', value: 0, target: 'one_ally', statusCured: ['poison', 'bleeding'] },
      },
      {
        uid: genUid(), itemId: 'herb_green', name: 'Erba Verde', description: 'Un\'erba medicinale. Ripristina 30 HP.',
        type: 'healing', rarity: 'common', icon: '🌿', usable: true, equippable: false, quantity: 3,
        effect: { type: 'heal', value: 30, target: 'self' },
      },
    ],
  },
  {
    id: 'dps',
    name: 'DPS',
    displayName: 'Jax Draven',
    description: 'Attaccante veloce e letale. Specializzato nell\'infliggere il massimo danno possibile in tempi brevi.',
    maxHp: 110,
    atk: 22,
    def: 9,
    spd: 12,
    specialName: 'Colpo Mortale',
    specialDescription: 'Un attacco mirato e devastante che infligge danni critici massimi.',
    specialCost: 18,
    special2Name: 'Raffica',
    special2Description: 'Spara una raffica che colpisce il bersaglio principale e danneggia anche gli altri nemici vicini.',
    special2Cost: 22,
    passiveDescription: 'Precisione: +15% di probabilità di infliggere colpi critici.',
    portraitEmoji: '⚔️',
    startingItems: [
      {
        uid: genUid(), itemId: 'pistol', name: 'Pistola M1911', description: 'Una pistola affidabile. Danni discreti a distanza.',
        type: 'weapon', rarity: 'uncommon', icon: '🔫', usable: false, equippable: true, quantity: 1,
        weaponStats: { itemId: 'pistol', name: 'Pistola M1911', type: 'ranged', ammoType: 'ammo_pistol', modSlots: [], effects: [{ type: 'buff_stat', trigger: 'on_equip', target: 'self', stat: 'atk', amount: 8, flat: true }] },
      },
      {
        uid: genUid(), itemId: 'ammo_pistol', name: 'Munizioni 9mm', description: 'Un pacco di munizioni per pistola.',
        type: 'ammo', rarity: 'common', icon: '📦', usable: true, equippable: false, quantity: 6,
      },
      {
        uid: genUid(), itemId: 'herb_green', name: 'Erba Verde', description: 'Un\'erba medicinale. Ripristina 30 HP.',
        type: 'healing', rarity: 'common', icon: '🌿', usable: true, equippable: false, quantity: 1,
        effect: { type: 'heal', value: 30, target: 'self' },
      },
    ],
  },
  {
    id: 'control',
    name: 'Controllo',
    displayName: 'Cassian Veyra',
    description: 'Esperto di tattiche di contenimento e manipolazione del campo di battaglia. Debilita i nemici con veleno, stordimento e dispositivi sonici.',
    maxHp: 100,
    atk: 14,
    def: 10,
    spd: 11,
    specialName: 'Gas Venefico',
    specialDescription: 'Lancia una granata di gas che avvelena tutti i nemici e riduce la loro velocità per due turni.',
    specialCost: 20,
    special2Name: 'Cristalli Sonici',
    special2Description: 'Attiva un dispositivo sonico che stordisce il bersaglio e infligge danni moderati.',
    special2Cost: 15,
    passiveDescription: 'Tattico: +20% probabilità di applicare status negativi (veleno, sanguinamento, stordimento).',
    portraitEmoji: '🎯',
    startingItems: [
      {
        uid: genUid(), itemId: 'combat_knife', name: 'Coltello da Combattimento', description: 'Un coltello militare affilato.',
        type: 'weapon', rarity: 'uncommon', icon: '🗡️', usable: false, equippable: true, quantity: 1,
        weaponStats: { itemId: 'combat_knife', name: 'Coltello da Combattimento', type: 'melee', modSlots: [], effects: [{ type: 'buff_stat', trigger: 'on_equip', target: 'self', stat: 'atk', amount: 10, flat: true }, { type: 'apply_status', trigger: 'on_hit', target: 'enemy', statusType: 'bleeding', chance: 25 }] },
      },
      {
        uid: genUid(), itemId: 'antidote', name: 'Antidoto', description: 'Cura avvelenamento.',
        type: 'antidote', rarity: 'common', icon: '💉', usable: true, equippable: false, quantity: 3,
        effect: { type: 'cure', value: 0, target: 'self', statusCured: ['poison'] },
      },
      {
        uid: genUid(), itemId: 'flashlight', name: 'Torcia', description: 'Una torcia per illuminare le tenebre.',
        type: 'utility', rarity: 'common', icon: '🔦', usable: true, equippable: false, quantity: 1,
      },
    ],
  },
  {
    id: 'survivor',
    name: 'Sopravvissuta',
    displayName: 'Sofia Reyes',
    description: 'Ibrido supporto/combatente che può mantenere in vita il gruppo. Versatile e adattabile, eccelle nel curare e rimuovere status negativi, con la capacità di potenziarsi in emergenza.',
    maxHp: 120,
    atk: 14,
    def: 10,
    spd: 10,
    specialName: 'Soccorso Rapido',
    specialDescription: 'Presta cure rapide al compagno più ferito, pulendo le condizioni negative e rafforzandone la difesa.',
    specialCost: 12,
    special2Name: 'Segnalazione Emergenza',
    special2Description: 'Attiva un segnale di emergenza che potenzia le capacità fisiche, conferendo adrenalina e aumentando attacco e velocità.',
    special2Cost: 18,
    passiveDescription: 'Adattabilità: +10% efficacia a tutti gli oggetti curativi usati da questo personaggio.',
    portraitEmoji: '🔦',
    startingItems: [
      {
        uid: genUid(), itemId: 'combat_knife', name: 'Coltello da Combattimento', description: 'Un coltello militare affilato.',
        type: 'weapon', rarity: 'uncommon', icon: '🗡️', usable: false, equippable: true, quantity: 1,
        weaponStats: { itemId: 'combat_knife', name: 'Coltello da Combattimento', type: 'melee', modSlots: [], effects: [{ type: 'buff_stat', trigger: 'on_equip', target: 'self', stat: 'atk', amount: 10, flat: true }, { type: 'apply_status', trigger: 'on_hit', target: 'enemy', statusType: 'bleeding', chance: 25 }] },
      },
      {
        uid: genUid(), itemId: 'bandage', name: 'Benda', description: 'Una benda per fermare le emorragie. Ripristina 25 HP.',
        type: 'healing', rarity: 'common', icon: '🩹', usable: true, equippable: false, quantity: 2,
        effect: { type: 'heal', value: 25, target: 'self' },
      },
      {
        uid: genUid(), itemId: 'herb_green', name: 'Erba Verde', description: 'Un\'erba medicinale. Ripristina 30 HP.',
        type: 'healing', rarity: 'common', icon: '🌿', usable: true, equippable: false, quantity: 1,
        effect: { type: 'heal', value: 30, target: 'self' },
      },
      {
        uid: genUid(), itemId: 'flashlight', name: 'Torcia', description: 'Una torcia che può accecare temporaneamente un nemico.',
        type: 'utility', rarity: 'common', icon: '🔦', usable: false, equippable: false, quantity: 1,
      },
      {
        uid: genUid(), itemId: 'lockpick', name: 'Giravite', description: 'Un giravite multiuso. Apre porte chiuse.',
        type: 'utility', rarity: 'common', icon: '🔧', usable: false, equippable: false, quantity: 1,
      },
    ],
  },
];
