import { EnemyDefinition, BossPhase, SpecialEffect } from '@/game/types';

export const SEED_ENEMIES: Record<string, EnemyDefinition> = {
  zombie: {
    id: 'zombie',
    name: 'Zombie',
    description: 'Un cittadino di Raccoon City trasformato dal virus T. Lento ma resistente.',
    variantGroup: 'zombie',
    maxHp: 60,
    atk: 12,
    def: 4,
    spd: 3,
    icon: '🧟',
    expReward: 15,
    isBoss: false,
    lootTable: [
      { itemId: 'herb_green', chance: 30, quantity: 1 },
      { itemId: 'bandage', chance: 40, quantity: 1 },
      { itemId: 'ammo_pistol', chance: 20, quantity: 3 },
    ],
    abilities: [
      { name: 'Morso', description: 'Un morso infetto.', power: 1.0, chance: 60, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 25, duration: 3 }] },
      { name: 'Artigliata', description: 'Un colpo con gli artigli insanguinati.', power: 0.8, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.8 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 20, duration: 3 }] },
      { name: 'Trascinamento', description: 'Il zombie cerca di afferrare la preda.', power: 0.6, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.6 }] },
    ],
  },
  zombie_female: {
    id: 'zombie_female',
    name: 'Zombie Donna',
    description: 'Una donna trasformata dal virus T. I vestiti strappati rivelano segni di morsicature.',
    maxHp: 50,
    atk: 11,
    def: 3,
    spd: 4,
    icon: '👩',
    expReward: 14,
    isBoss: false,
    variantGroup: 'zombie',
    lootTable: [
      { itemId: 'herb_green', chance: 25, quantity: 1 },
      { itemId: 'bandage', chance: 35, quantity: 1 },
      { itemId: 'antidote', chance: 15, quantity: 1 },
    ],
    abilities: [
      { name: 'Morso', description: 'Un morso infetto.', power: 1.0, chance: 55, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 20, duration: 3 }] },
      { name: 'Artigliata', description: 'Un colpo con le unghie insanguinate.', power: 0.7, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.7 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 15, duration: 3 }] },
      { name: 'Urlo', description: 'Un urlo stridulo che disorienta.', power: 0.3, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.3 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 20, duration: 1 }] },
    ],
  },
  zombie_soldier: {
    id: 'zombie_soldier',
    name: 'Zombie Soldato UBCS',
    description: 'Un mercenario UBCS caduto in battaglia. Il giubbotto antiproiettile parzialmente resiste ai colpi.',
    maxHp: 80,
    atk: 15,
    def: 8,
    spd: 3,
    icon: '🪖',
    expReward: 22,
    isBoss: false,
    variantGroup: 'zombie',
    lootTable: [
      { itemId: 'ammo_pistol', chance: 35, quantity: 5 },
      { itemId: 'ammo_shotgun', chance: 15, quantity: 2 },
      { itemId: 'ammo_machinegun', chance: 12, quantity: 3 },
      { itemId: 'bandage', chance: 30, quantity: 1 },
      { itemId: 'combat_knife', chance: 5, quantity: 1 },
    ],
    abilities: [
      { name: 'Colpo di Fucile', description: 'Sparacora un colpo con il fucile d\'assalto.', power: 1.2, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.2 }] },
      { name: 'Morso', description: 'Un morso infetto.', power: 0.9, chance: 45, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 25, duration: 3 }] },
      { name: 'Carica', description: 'Carica con il giubbotto antiproiettile.', power: 1.0, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 15, duration: 1 }] },
      { name: 'Coltello Rotante', description: 'Lancia il coltello da combattimento.', power: 0.8, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.8 }] },
    ],
  },
  zombie_doctor: {
    id: 'zombie_doctor',
    name: 'Zombie Dottore',
    description: 'Un ricercatore della Umbrella infettato dal virus T. Conosceva i segreti del laboratorio.',
    maxHp: 55,
    atk: 10,
    def: 3,
    spd: 4,
    icon: '🩺',
    expReward: 18,
    isBoss: false,
    variantGroup: 'zombie',
    lootTable: [
      { itemId: 'antidote', chance: 25, quantity: 1 },
      { itemId: 'herb_green', chance: 30, quantity: 1 },
      { itemId: 'first_aid', chance: 20, quantity: 1 },
      { itemId: 'key_lab', chance: 5, quantity: 1 },
    ],
    abilities: [
      { name: 'Siringa Infetta', description: 'Lancia una siringa contaminata.', power: 0.8, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.8 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 45, duration: 3 }] },
      { name: 'Morso', description: 'Un morso infetto.', power: 0.9, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 20, duration: 3 }] },
      { name: 'Bisturi', description: 'Colpisce con un bisturi arrugginito.', power: 0.7, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.7 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 30, duration: 3 }] },
      { name: 'Urlo', description: 'Un urlo disumano.', power: 0.2, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.2 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 25, duration: 1 }] },
    ],
  },
  zombie_dog: {
    id: 'zombie_dog',
    name: 'Cerbero',
    description: 'Un cane da guardia della Umbrella infettato dal virus T. Veloce e aggressivo.',
    variantGroup: 'cerberus',
    maxHp: 40,
    atk: 16,
    def: 2,
    spd: 10,
    icon: '🐕',
    expReward: 20,
    isBoss: false,
    lootTable: [
      { itemId: 'bandage', chance: 35, quantity: 1 },
      { itemId: 'herb_green', chance: 20, quantity: 1 },
    ],
    abilities: [
      { name: 'Attacco Rapido', description: 'Un balzo fulmineo.', power: 1.0, chance: 50, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }] },
      { name: 'Morso Velenoso', description: 'Un morso tossico.', power: 0.9, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 35, duration: 3 }] },
      { name: 'Ringhio', description: 'Un ringhio spaventoso.', power: 0.3, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.3 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 30, duration: 1 }] },
    ],
  },
  cerberus_alpha: {
    id: 'cerberus_alpha',
    name: 'Cerbero Alpha',
    description: 'Un esemplare di Cerbero sperimentale, più grande e aggressivo del normale. I muscoli sono esposti e pulsano.',
    maxHp: 70,
    atk: 22,
    def: 4,
    spd: 12,
    icon: '🐺',
    expReward: 35,
    isBoss: false,
    variantGroup: 'cerberus',
    lootTable: [
      { itemId: 'herb_green', chance: 25, quantity: 1 },
      { itemId: 'antidote', chance: 20, quantity: 1 },
      { itemId: 'ammo_shotgun', chance: 15, quantity: 3 },
    ],
    abilities: [
      { name: 'Morso Devastante', description: 'Un morso che squarcia la carne.', power: 1.3, chance: 45, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.3 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 40, duration: 3 }] },
      { name: 'Carica Brutale', description: 'Una carica impossibile da schivare.', power: 1.5, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5, noMiss: true }] },
      { name: 'Ringhio Infernale', description: 'Un ringhio che gela il sangue.', power: 0.4, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.4 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 40, duration: 1 }] },
      { name: 'Artigli Multipli', description: 'Una serie di artigliate rapide.', power: 0.9, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 25, duration: 3 }] },
    ],
  },
  licker: {
    id: 'licker',
    name: 'Licker',
    description: 'Una creatura con il cervello esposto e una lingua artigliata. Senza vista ma con udito finissimo.',
    variantGroup: 'licker',
    maxHp: 80,
    atk: 20,
    def: 5,
    spd: 9,
    icon: '👅',
    expReward: 30,
    isBoss: false,
    lootTable: [
      { itemId: 'herb_red', chance: 25, quantity: 1 },
      { itemId: 'first_aid', chance: 30, quantity: 1 },
      { itemId: 'combat_knife', chance: 10, quantity: 1 },
    ],
    abilities: [
      { name: 'Lingua Artigliata', description: 'La lingua si allunga e colpisce.', power: 1.2, chance: 45, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.2 }] },
      { name: 'Artiglio Devastante', description: 'Un colpo con gli artigli taglienti.', power: 1.0, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 40, duration: 3 }] },
      { name: 'Salto', description: 'Un salto mortale dalla parete.', power: 1.5, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5 }] },
    ],
  },
  licker_smasher: {
    id: 'licker_smasher',
    name: 'Licker Smasher',
    description: 'Un Licker di tipo T potenziato con massa muscolare eccessiva. Più lento ma i suoi colpi sono devastanti.',
    maxHp: 130,
    atk: 28,
    def: 8,
    spd: 6,
    icon: '👾',
    expReward: 45,
    isBoss: false,
    variantGroup: 'licker',
    lootTable: [
      { itemId: 'herb_red', chance: 30, quantity: 1 },
      { itemId: 'first_aid', chance: 25, quantity: 1 },
      { itemId: 'spray', chance: 15, quantity: 1 },
      { itemId: 'combat_knife', chance: 12, quantity: 1 },
    ],
    abilities: [
      { name: 'Pugno Terra', description: 'Un pugno che fa tremare il suolo.', power: 1.8, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.8 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 30, duration: 1 }] },
      { name: 'Lingua Artigliata', description: 'La lingua colpisce con forza brutale.', power: 1.4, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.4 }] },
      { name: 'Artiglio Squarciatore', description: 'Artigli che tagliano profondamente.', power: 1.6, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.6 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 50, duration: 3 }] },
      { name: 'Corpo a Corpo', description: 'Si lancie addosso alla preda.', power: 1.2, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.2 }] },
    ],
  },
  licker_crawler: {
    id: 'licker_crawler',
    name: 'Licker Crawler',
    description: 'Un Licker elitario dalle membra allungate. Si muove sulle pareti e colpisce dalla oscurità con velocità letale.',
    maxHp: 65,
    atk: 22,
    def: 3,
    spd: 13,
    icon: '🦎',
    expReward: 38,
    isBoss: false,
    variantGroup: 'licker',
    lootTable: [
      { itemId: 'herb_red', chance: 20, quantity: 1 },
      { itemId: 'ammo_pistol', chance: 30, quantity: 5 },
      { itemId: 'lockpick', chance: 10, quantity: 1 },
    ],
    abilities: [
      { name: 'Attacco dal Soffitto', description: 'Cala dall\'alto senza preavviso.', power: 1.6, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.6 }] },
      { name: 'Lingua Fulminea', description: 'La lingua colpisce prima che si possa reagire.', power: 1.2, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.2 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 35, duration: 3 }] },
      { name: 'Scatto sulle Pareti', description: 'Si muove sulle pareti e attacca di lato.', power: 1.0, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }] },
      { name: 'Morso Velenoso', description: 'Un morso con fluido tossico.', power: 0.9, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 50, duration: 3 }] },
    ],
  },
  hunter: {
    id: 'hunter',
    name: 'Hunter',
    description: 'Un B.O.W. (Bio Organic Weapon) creato dalla Umbrella. Mortale e intelligente.',
    variantGroup: 'hunter',
    maxHp: 120,
    atk: 24,
    def: 8,
    spd: 11,
    icon: '🦎',
    expReward: 45,
    isBoss: false,
    lootTable: [
      { itemId: 'herb_red', chance: 35, quantity: 1 },
      { itemId: 'shotgun', chance: 8, quantity: 1 },
      { itemId: 'grenade_launcher', chance: 7, quantity: 1 },
      { itemId: 'ammo_grenade', chance: 10, quantity: 1 },
      { itemId: 'spray', chance: 15, quantity: 1 },
      { itemId: 'antidote', chance: 30, quantity: 1 },
    ],
    abilities: [
      { name: 'Artigli Fendenti', description: 'Artigli che tagliano attraverso qualsiasi armatura.', power: 1.3, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.3 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 50, duration: 3 }] },
      { name: 'Salto Mortale', description: 'Un attacco dall\'alto devastante.', power: 1.8, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.8 }] },
      { name: 'Ruggito', description: 'Un ruggito terrificante.', power: 0.4, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.4 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 40, duration: 1 }] },
      { name: 'Scatto', description: 'Si muove velocemente per attaccare.', power: 1.0, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }] },
    ],
  },
  tyrant_boss: {
    id: 'tyrant_boss',
    name: 'T-103 Tyrant',
    description: 'Il Terminus. Un Bio Organic Weapon di classe Tyrant mandato a eliminare tutti i sopravvissuti.',
    variantGroup: 'tyrant',
    maxHp: 350,
    atk: 30,
    def: 15,
    spd: 7,
    icon: '👹',
    expReward: 100,
    isBoss: true,
    lootTable: [
      { itemId: 'magnum', chance: 40, quantity: 1 },
      { itemId: 'rocket_launcher', chance: 5, quantity: 1 },
      { itemId: 'spray', chance: 60, quantity: 2 },
    ],
    abilities: [
      { name: 'Pugno Devastante', description: 'Un pugno che squarcia l\'aria.', power: 1.5, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5 }] },
      { name: 'Carica', description: 'Una carica inarrestabile.', power: 2.0, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.0, noMiss: true }] },
      { name: 'Artiglio Mortale', description: 'Artigli che strappano la carne.', power: 1.8, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.8 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 60, duration: 3 }] },
      { name: 'Urlo', description: 'Un urlo che fa tremare le pareti.', power: 0.5, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.5 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 50, duration: 1 }] },
      { name: 'Presa Mortale', description: 'Afferra la vittima e la schiaccia.', power: 2.5, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.5, noMiss: true }] },
    ],
  },
  nemesis_boss: {
    id: 'nemesis_boss',
    name: 'NEMESIS',
    description: 'S.T.A.R.S... Il Nemico Puro. Un Tyrant potenziato con intelligenza e armamenti pesanti.',
    variantGroup: 'nemesis',
    maxHp: 500,
    atk: 35,
    def: 18,
    spd: 9,
    icon: '💀',
    expReward: 200,
    isBoss: true,
    lootTable: [
      { itemId: 'magnum', chance: 50, quantity: 1 },
      { itemId: 'rocket_launcher', chance: 5, quantity: 1 },
      { itemId: 'spray', chance: 80, quantity: 3 },
      { itemId: 'ammo_magnum', chance: 60, quantity: 8 },
      { itemId: 'ammo_grenade', chance: 15, quantity: 2 },
    ],
    abilities: [
      { name: 'Razzo', description: 'Lancia un razzo esplosivo.', power: 2.5, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.5 }] },
      { name: 'Pugno Tentacolo', description: 'Un tentacolo emerge dal braccio.', power: 2.0, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.0 }] },
      { name: 'S.T.A.R.S.!', description: 'Un urlo terrificante seguito da una carica.', power: 1.5, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 45, duration: 1 }] },
      { name: 'Artiglio Multipli', description: 'Una raffica di artigli.', power: 1.8, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.8 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 50, duration: 3 }] },
      { name: 'Devastazione', description: 'Distrugge tutto ciò che lo circonda.', power: 3.0, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'all_enemies', powerMultiplier: 3.0 }] },
    ],
  },
  chimera: {
    id: 'chimera',
    name: 'Chimera',
    description: 'Un ibrido creato incrociando DNA umano con geni di pipistrello e insetto. Si appiccica ai soffitti e attacca dall\'alto.',
    variantGroup: 'chimera',
    maxHp: 70,
    atk: 22,
    def: 3,
    spd: 14,
    icon: '🦇',
    expReward: 40,
    isBoss: false,
    lootTable: [
      { itemId: 'ammo_pistol', chance: 20, quantity: 4 },
      { itemId: 'bandage', chance: 15, quantity: 1 },
      { itemId: 'herb_green', chance: 10, quantity: 1 },
    ],
    abilities: [
      { name: 'Artiglio Aereo', description: 'Si lancia dal soffitto con artigli affilati.', power: 1.3, chance: 45, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.3 }] },
      { name: 'Volo Rasente', description: 'Un attacco rapido a bassa quota.', power: 1.0, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 30, duration: 3 }] },
      { name: 'Urllo Sonico', description: 'Un grido acuto che disorienta la preda.', power: 0.4, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.4 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 35, duration: 1 }] },
      { name: 'Morsi Multipli', description: 'Una serie di morsi veloci.', power: 0.8, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.8 }] },
    ],
  },
  ivy: {
    id: 'ivy',
    name: 'Ivy',
    description: 'Una pianta mutata dal virus T. Le sue liane si muovono come tentacoli e sprigionano un gas velenoso. Immobile ma letale a distanza ravvicinata.',
    variantGroup: 'ivy',
    maxHp: 100,
    atk: 18,
    def: 6,
    spd: 5,
    icon: '🌿',
    expReward: 42,
    isBoss: false,
    lootTable: [
      { itemId: 'herb_green', chance: 30, quantity: 1 },
      { itemId: 'herb_red', chance: 15, quantity: 1 },
      { itemId: 'antidote', chance: 15, quantity: 1 },
    ],
    abilities: [
      { name: 'Liana Avvolgente', description: 'Le liane si avvolgono attorno alla preda.', power: 1.2, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.2 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 50, duration: 3 }] },
      { name: 'Gas Velenoso', description: 'Rilascia una nuvola di spore tossiche.', power: 0.9, chance: 35, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.9 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 60, duration: 4 }] },
      { name: 'Schianto Radicale', description: 'Le radici emergono dal suolo con forza.', power: 1.5, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5 }] },
      { name: 'Spine Esplosive', description: 'Lancia spine velenose in tutte le direzioni.', power: 0.7, chance: 5, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.7 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 40, duration: 2 }] },
    ],
  },
  g_adult: {
    id: 'g_adult',
    name: 'G-Adult',
    description: 'Una forma evoluta del G-virus. Un essere massiccio con tentacoli e un\'armatura organica. Più forte e resistente di qualsiasi creatura T.',
    variantGroup: 'g_adult',
    maxHp: 160,
    atk: 26,
    def: 10,
    spd: 4,
    icon: '🐛',
    expReward: 55,
    isBoss: false,
    lootTable: [
      { itemId: 'ammo_shotgun', chance: 25, quantity: 4 },
      { itemId: 'spray', chance: 10, quantity: 1 },
      { itemId: 'first_aid', chance: 10, quantity: 1 },
    ],
    abilities: [
      { name: 'Sputo Acido', description: 'Sputa un getto di acido corrosivo.', power: 1.4, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.4 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 35, duration: 3 }] },
      { name: 'Tentacolo Schiacciante', description: 'Un tentacolo massiccio colpisce con forza devastante.', power: 1.8, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.8 }] },
      { name: 'Carica Mutante', description: 'Si lancia con tutto il peso del corpo.', power: 2.0, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.0, noMiss: true }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 25, duration: 1 }] },
      { name: 'Rigenerazione', description: 'Le cellule si rigenerano velocemente.', power: 0.5, chance: 10, effects: [{ type: 'heal', trigger: 'on_use', target: 'self', amount: 25 }] },
    ],
  },
  licker_alpha: {
    id: 'licker_alpha',
    name: 'Licker Alpha',
    description: 'Un Licker evoluto con muscoli ipertrofici e una lingua ancora più letale. La mutazione ha potenziato la sua velocità e letalità.',
    variantGroup: 'licker',
    maxHp: 110,
    atk: 25,
    def: 6,
    spd: 11,
    icon: '👅',
    expReward: 48,
    isBoss: false,
    lootTable: [
      { itemId: 'ammo_magnum', chance: 15, quantity: 3 },
      { itemId: 'herb_green', chance: 20, quantity: 1 },
      { itemId: 'mod_fire_rounds', chance: 8, quantity: 1 },
    ],
    abilities: [
      { name: 'Lingua Mortale', description: 'La lingua colpisce con precisione chirurgica.', power: 1.5, chance: 40, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.5 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 45, duration: 3 }] },
      { name: 'Artiglio Emorragico', description: 'Artigli che causano emorragie massive.', power: 1.3, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.3 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 55, duration: 4 }] },
      { name: 'Balzo Omicida', description: 'Un salto dall\'alto con impatto devastante.', power: 2.0, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.0 }] },
      { name: 'Ruggito Sismico', description: 'Un ruggito che fa vibrare le pareti.', power: 0.5, chance: 10, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.5 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 40, duration: 1 }] },
    ],
  },
  // #24 - BOSS SEGRETO: B.O.W. Proto Tyrant (sperimentale, found in secret lab)
  proto_tyrant: {
    id: 'proto_tyrant',
    name: 'B.O.W. Proto-Tyrant',
    description: 'Un esemplare sperimentale di Tyrant mai completato. Il corpo è deforme e coperto di tubi. Trovato nel laboratorio segreto della Umbrella.',
    variantGroup: 'tyrant',
    maxHp: 450,
    atk: 38,
    def: 12,
    spd: 8,
    icon: '🧪',
    expReward: 250,
    isBoss: true,
    lootTable: [
      { itemId: 'magnum', chance: 60, quantity: 1 },
      { itemId: 'rocket_launcher', chance: 15, quantity: 1 },
      { itemId: 'spray', chance: 90, quantity: 3 },
      { itemId: 'ammo_magnum', chance: 70, quantity: 10 },
      { itemId: 'ammo_grenade', chance: 20, quantity: 3 },
      { itemId: 'bag_medium', chance: 25, quantity: 1 },
    ],
    abilities: [
      { name: 'Sbatacio Anomalo', description: 'Un attacco con arti innaturali.', power: 1.6, chance: 30, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 1.6 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'bleeding', chance: 55, duration: 3 }] },
      { name: 'Tentacolo Infetto', description: 'Un tentacolo coperto di bolline.', power: 2.0, chance: 25, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.0 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'poison', chance: 50, duration: 3 }] },
      { name: 'Urlo Agonizzante', description: 'Un urlo che incrina il cervello.', power: 0.6, chance: 15, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 0.6 }, { type: 'apply_status', trigger: 'on_use', target: 'enemy', statusType: 'stunned', chance: 55, duration: 1 }] },
      { name: 'Scarica Brutale', description: 'Una carica che spacca il pavimento.', power: 2.2, chance: 20, effects: [{ type: 'deal_damage', trigger: 'on_use', target: 'enemy', powerMultiplier: 2.2 }] },
      { name: 'Mutazione Rapida', description: 'Si rigenera e diventa più forte.', power: 1.0, chance: 10, effects: [{ type: 'heal', trigger: 'on_use', target: 'self', amount: 30 }] },
    ],
  },
};
