export const SEED_RECIPES = [
  // ── Herb Combinations (Classic RE style) ──
  {
    id: 'craft_herb_mixed',
    name: 'Erba Mista (V+R)',
    description: 'Erba Verde + Erba Rossa → Erba Mista. Cura potente con rimozione status.',
    icon: '🌿',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 1 }, { itemId: 'herb_red', quantity: 1 }]),
    resultItemId: 'herb_mixed',
    resultQty: 1,
    difficulty: 'easy',
    pointCost: 3,
    sortOrder: 1,
  },
  {
    id: 'craft_herb_mixed_double',
    name: 'Erba Mista (V+V)',
    description: 'Due Erbe Verdi per una cura più potente.',
    icon: '🌿',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 2 }]),
    resultItemId: 'herb_mixed',
    resultQty: 1,
    difficulty: 'easy',
    pointCost: 3,
    sortOrder: 2,
  },
  {
    id: 'craft_spray_mixed',
    name: 'Spray (Mista + Rossa)',
    description: 'Erba Mista + Erba Rossa → Spray Medicale potente.',
    icon: '🧪',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_mixed', quantity: 1 }, { itemId: 'herb_red', quantity: 1 }]),
    resultItemId: 'spray',
    resultQty: 1,
    difficulty: 'medium',
    pointCost: 5,
    sortOrder: 3,
  },
  {
    id: 'craft_spray_red',
    name: 'Spray Potenziato',
    description: '2 Erbe Rosse → Spray Medicale con potenziamento.',
    icon: '❤️‍🔥',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_red', quantity: 2 }]),
    resultItemId: 'spray',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointCost: 8,
    sortOrder: 4,
  },
  // ── Ammunition Recycling ──
  {
    id: 'craft_shotgun_shells',
    name: 'Cartucce da Fucile',
    description: 'Ricicla 3 munizioni da pistola in 1 cartuccia da fucile.',
    icon: '🔶',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'ammo_pistol', quantity: 3 }]),
    resultItemId: 'ammo_shotgun',
    resultQty: 1,
    difficulty: 'medium',
    pointCost: 5,
    sortOrder: 5,
  },
  {
    id: 'craft_magnum_rounds',
    name: 'Munizioni .357 Magnum',
    description: '2 cartucce da fucile → 1 munizione magnum devastante.',
    icon: '🔴',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'ammo_shotgun', quantity: 2 }]),
    resultItemId: 'ammo_magnum',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointCost: 8,
    sortOrder: 6,
  },
  {
    id: 'craft_grenade_40mm',
    name: 'Granate 40mm',
    description: '5 Munizioni Pistola + Erba Verde → 1 Granata esplosiva.',
    icon: '💣',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'ammo_pistol', quantity: 5 }, { itemId: 'herb_green', quantity: 1 }]),
    resultItemId: 'ammo_grenade',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointCost: 8,
    sortOrder: 7,
  },
  // ── Medical ──
  {
    id: 'craft_antidote_spray',
    name: 'Spray Antidoto',
    description: 'Erba Verde + Antidoto → 2 Antidoti potenziati.',
    icon: '💉',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 1 }, { itemId: 'antidote', quantity: 1 }]),
    resultItemId: 'antidote',
    resultQty: 2,
    difficulty: 'easy',
    pointCost: 3,
    sortOrder: 8,
  },
  {
    id: 'craft_first_aid',
    name: 'Kit Pronto Soccorso',
    description: '3 Bende → Kit medico completo con cura totale.',
    icon: '🩹',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'bandage', quantity: 3 }]),
    resultItemId: 'first_aid',
    resultQty: 1,
    difficulty: 'easy',
    pointCost: 3,
    sortOrder: 9,
  },
  // ── Boosters & Special Items ──
  {
    id: 'craft_adrenaline',
    name: 'Iniezione di Adrenalina',
    description: 'Benda + Erba Verde → Iniezione di Adrenalina. +20 ATK temporaneo in combattimento.',
    icon: '💉',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'bandage', quantity: 1 }, { itemId: 'herb_green', quantity: 1 }]),
    resultItemId: 'adrenaline_shot',
    resultQty: 1,
    difficulty: 'medium',
    hidden: true,
    pointCost: 5,
    sortOrder: 10,
  },
  {
    id: 'craft_defense_pill',
    name: 'Pillola Difensiva',
    description: 'Erba Rossa + Antidoto → 2 Pillole Difensive. +15 DEF temporaneo.',
    icon: '💊',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_red', quantity: 1 }, { itemId: 'antidote', quantity: 1 }]),
    resultItemId: 'defense_pill',
    resultQty: 2,
    difficulty: 'medium',
    hidden: true,
    pointCost: 5,
    sortOrder: 11,
  },
  {
    id: 'craft_pipe_bomb',
    name: 'Bomba Artigianale',
    description: '3 Munizioni Pistola + Erba Verde → Bomba Artigianale. 50 danni a tutti i nemici.',
    icon: '💣',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'ammo_pistol', quantity: 3 }, { itemId: 'herb_green', quantity: 1 }]),
    resultItemId: 'pipe_bomb',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointCost: 8,
    sortOrder: 12,
  },
  // ── Advanced Healing ──
  {
    id: 'craft_spray_super',
    name: 'Spray Super',
    description: 'Spray + Erba Rossa → 2 Kit di Pronto Soccorso. Cura totale con rimozione status.',
    icon: '❤️‍🔥',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'spray', quantity: 1 }, { itemId: 'herb_red', quantity: 1 }]),
    resultItemId: 'first_aid',
    resultQty: 2,
    difficulty: 'hard',
    hidden: true,
    pointCost: 8,
    sortOrder: 13,
  },
  // ── Advanced Ammo ──
  {
    id: 'craft_machinegun_ammo',
    name: 'Munizioni 5.56mm',
    description: '6 Munizioni Pistola → 2 Munizioni Mitragliatrice. Riciclaggio avanzato.',
    icon: '🟡',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'ammo_pistol', quantity: 6 }]),
    resultItemId: 'ammo_machinegun',
    resultQty: 2,
    difficulty: 'medium',
    hidden: true,
    pointCost: 5,
    sortOrder: 14,
  },
  // ── Resource Conversion ──
  {
    id: 'craft_mega_bandage',
    name: 'Spray Mega',
    description: 'Kit Pronto Soccorso + 2 Erbe Verdi → 2 Spray Mediali. Cura ad alto livello.',
    icon: '🧴',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'first_aid', quantity: 1 }, { itemId: 'herb_green', quantity: 2 }]),
    resultItemId: 'spray',
    resultQty: 2,
    difficulty: 'medium',
    hidden: true,
    pointCost: 5,
    sortOrder: 15,
  },
  // ── #8 Point-Only Recipes ──
  {
    id: 'craft_bio_ammo',
    name: 'Munizioni Biohazard',
    description: 'Ricicla materiali contaminati in 6 granate esplosive.',
    icon: '☢️',
    category: 'ammo',
    ingredients: JSON.stringify([]),
    resultItemId: 'ammo_grenade',
    resultQty: 6,
    difficulty: 'hard',
    hidden: true,
    pointOnly: true,
    pointCost: 12,
    sortOrder: 16,
  },
  {
    id: 'craft_viral_sample',
    name: 'Campionamento Virale',
    description: 'Crea un Lanciarazzi da materiali di laboratorio recuperati.',
    icon: '🚀',
    category: 'ammo',
    ingredients: JSON.stringify([]),
    resultItemId: 'rocket_launcher',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointOnly: true,
    pointCost: 15,
    sortOrder: 17,
  },
  {
    id: 'craft_ultimate_mix',
    name: 'Spray Ultimato',
    description: 'Produce uno Spray con qualità garantita maestra.',
    icon: '✨',
    category: 'healing',
    ingredients: JSON.stringify([]),
    resultItemId: 'spray',
    resultQty: 1,
    difficulty: 'hard',
    hidden: true,
    pointOnly: true,
    pointCost: 10,
    forceMasterQuality: true,
    sortOrder: 18,
  },
];
