export const SEED_RECIPES = [
  {
    id: 'craft_pistol_ammo',
    name: 'Munizioni Pistola',
    description: 'Crafta munizioni 9mm per la pistola.',
    icon: '🔶',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'gunpowder', quantity: 1 }, { itemId: 'metal_scrap', quantity: 1 }]),
    resultItemId: 'ammo_pistol',
    resultQty: 5,
    difficulty: 'easy',
    sortOrder: 1,
  },
  {
    id: 'craft_shotgun_shells',
    name: 'Munizioni Fucile',
    description: 'Crafta cartucce per il fucile a pompa.',
    icon: '🔷',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'gunpowder', quantity: 2 }, { itemId: 'metal_scrap', quantity: 2 }]),
    resultItemId: 'ammo_shotgun',
    resultQty: 3,
    difficulty: 'medium',
    sortOrder: 2,
  },
  {
    id: 'craft_magnum_rounds',
    name: 'Munizioni Magnum',
    description: 'Crafta munizioni .357 per il magnum.',
    icon: '🔴',
    category: 'ammo',
    ingredients: JSON.stringify([{ itemId: 'gunpowder', quantity: 3 }, { itemId: 'metal_scrap', quantity: 3 }, { itemId: 'empty_shell', quantity: 1 }]),
    resultItemId: 'ammo_magnum',
    resultQty: 2,
    difficulty: 'hard',
    sortOrder: 3,
  },
  {
    id: 'craft_antidote',
    name: 'Antidoto',
    description: 'Crafta un antidoto contro il veleno.',
    icon: '💉',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 1 }, { itemId: 'distilled_water', quantity: 1 }]),
    resultItemId: 'crafted_antidote',
    resultQty: 1,
    difficulty: 'easy',
    sortOrder: 4,
  },
  {
    id: 'craft_strong_bandage',
    name: 'Cerotto Potente',
    description: 'Crafta una benda medica potenziata.',
    icon: '🩹',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 2 }, { itemId: 'alcohol', quantity: 1 }]),
    resultItemId: 'strong_bandage',
    resultQty: 1,
    difficulty: 'medium',
    sortOrder: 5,
  },
  {
    id: 'craft_strong_painkiller',
    name: 'Analgesico Forte',
    description: 'Crafta un potente antidolorifico.',
    icon: '💊',
    category: 'healing',
    ingredients: JSON.stringify([{ itemId: 'herb_green', quantity: 1 }, { itemId: 'herb_red', quantity: 1 }, { itemId: 'alcohol', quantity: 1 }]),
    resultItemId: 'strong_painkiller',
    resultQty: 1,
    difficulty: 'hard',
    sortOrder: 6,
  },
  {
    id: 'craft_stimulant',
    name: 'Stimolante',
    description: 'Crafta uno stimolante che aumenta la velocità temporaneamente.',
    icon: '⚡',
    category: 'booster',
    ingredients: JSON.stringify([{ itemId: 'distilled_water', quantity: 1 }, { itemId: 'gunpowder', quantity: 1 }]),
    resultItemId: 'stimulant',
    resultQty: 1,
    difficulty: 'easy',
    sortOrder: 7,
  },
  {
    id: 'craft_elastic_bandage',
    name: 'Benda Elastica',
    description: 'Crafta una benda con supporto elastico.',
    icon: '🩹',
    category: 'booster',
    ingredients: JSON.stringify([{ itemId: 'metal_scrap', quantity: 2 }, { itemId: 'herb_green', quantity: 1 }]),
    resultItemId: 'elastic_bandage',
    resultQty: 1,
    difficulty: 'medium',
    sortOrder: 8,
  },
  {
    id: 'craft_adrenaline',
    name: 'Adrenalina',
    description: 'Crafta una siringa di adrenalina per il combattimento.',
    icon: '💉',
    category: 'booster',
    ingredients: JSON.stringify([{ itemId: 'metal_scrap', quantity: 1 }, { itemId: 'distilled_water', quantity: 1 }, { itemId: 'alcohol', quantity: 1 }]),
    resultItemId: 'adrenaline_shot',
    resultQty: 1,
    difficulty: 'medium',
    sortOrder: 9,
  },
];
