export const SEED_SECRET_ROOMS = [
  {
    id: 'secret_rpd_armory',
    locationId: 'rpd_station',
    name: 'Armeria Segreta RPD',
    description: 'Un\'armeria nascosta dietro una parete finta nell\'ufficio del capitano. Contiene equipaggiamento militare d\'epoca.',
    discoveryMethod: 'document',
    requiredDocumentId: 'doc_rpd_diary',
    requiredNpcQuestId: null,
    searchChance: 0,
    hint: 'Il diario del capitano menziona un pannello rimovibile... "Dietro la foto di gruppo si trova qualcosa che non dovrebbe essere lì. Forse un meccanismo nascosto?"',
    lootTable: JSON.stringify([
      { itemId: 'combat_knife', chance: 80, quantity: 1 },
      { itemId: 'ammo_shotgun', chance: 60, quantity: 2 },
    ]),
    uniqueItemId: 'ammo_magnum',
    uniqueItemQuantity: 3,
    sortOrder: 1,
  },
  {
    id: 'secret_sewers_bunker',
    locationId: 'sewers',
    name: 'Bunker Sotto le Fogne',
    description: 'Un bunker abbandonato costruito durante la Guerra Fredda, nascosto dietro una grata arrugginita nelle profondità delle fogne.',
    discoveryMethod: 'search',
    requiredDocumentId: null,
    requiredNpcQuestId: null,
    searchChance: 15,
    hint: 'Un getto d\'aria anomalo proviene da una grata arrugginita. Forse c\'è qualcosa oltre...',
    lootTable: JSON.stringify([
      { itemId: 'first_aid', chance: 70, quantity: 1 },
      { itemId: 'ammo_pistol', chance: 50, quantity: 5 },
    ]),
    uniqueItemId: 'bag_medium',
    uniqueItemQuantity: 1,
    sortOrder: 2,
  },
  {
    id: 'secret_lab_birkin',
    locationId: 'laboratory',
    name: 'Laboratorio Segreto Birkin',
    description: 'Il laboratorio privato del Dr. Birkin, nascosto dietro un passaggio sigillato nel livello inferiore. Qui ha condotto gli esperimenti sul G-Virus.',
    discoveryMethod: 'npc_hint',
    requiredDocumentId: null,
    requiredNpcQuestId: 'quest_voss_data',
    searchChance: 0,
    hint: 'Il Dr. Voss menziona un passaggio segreto nel laboratorio... "Birkin nascondeva i suoi risultati migliori dietro il Level B-7. Trova il pannello con il codice 4817."',
    lootTable: JSON.stringify([
      { itemId: 'spray', chance: 80, quantity: 2 },
      { itemId: 'herb_mixed', chance: 60, quantity: 2 },
    ]),
    uniqueItemId: 'rocket_launcher',
    uniqueItemQuantity: 1,
    sortOrder: 3,
  },
];
