/**
 * App Versioning System
 * 
 * Semantic Versioning: MAJOR.MINOR.PATCH
 * - MAJOR: Breaking changes / major feature releases
 * - MINOR: New features (backwards compatible)
 * - PATCH: Bug fixes and small improvements
 * 
 * ⚠️ IMPORTANT: Every code change MUST update this file!
 * 
 * Format: { version, date, description }
 */

export const APP_VERSION = '1.22.2' as const;

export const VERSION_HISTORY: Array<{
  version: string;
  date: string;
  changes: string[];
}> = [
  {
    version: '1.0.0',
    date: '2025-03-04',
    changes: [
      'Sistema di versioning implementato',
      'Footer con versione dell\'applicazione',
    ],
  },
  {
    version: '1.0.1',
    date: '2025-03-04',
    changes: [
      'Fix footer che sovrapponeva il pannello titolo',
    ],
  },
  {
    version: '1.0.2',
    date: '2025-03-04',
    changes: [
      'Fix Colpo Mortale: ora colpisce correttamente il target selezionato',
      'Fix Raffica: ora applica il danno principale al target + danno collaterale agli altri',
      'Refactor handleDealDamage: risoluzione target primario all\'inizio, come attacco base',
    ],
  },
  {
    version: '1.0.3',
    date: '2025-03-04',
    changes: [
      'Fix log attacco base: non mostra più "usa [arma] ma non ha effetti" per armi con solo effetti passivi',
    ],
  },
  {
    version: '1.0.4',
    date: '2025-06-18',
    changes: [
      'Fix handleDealDamage: aggiunto fallback sicuro per effetti single-target quando la lookup per ID fallisce',
      'Fix resolveTargets: rimosso fallback per nome che poteva colpire il nemico sbagliato con nemici duplicati',
      'Fix executeEffectsInternal: aggiunto fallback definitionId per enemy re-instantiati',
      'Migliorato logging diagnostico per debug del targeting in combattimento',
    ],
  },
  {
    version: '1.0.5',
    date: '2025-06-20',
    changes: [
      'Fix critico store.ts: usava character.special1Id/special2Id invece di resolveSpecialId() per archetipi predefiniti',
      'Fix store.ts: risoluzione target per abilità speciali ora usa la stessa logica dell\'attacco base (solo nemici vivi, nessun fallback sbagliato)',
      'Fix Colpo Mortale: non mostra più "non ci sono bersagli validi" per archetipi predefiniti (DPS, Tank, Healer, Control)',
      'Fix Raffica: primo effetto ora infligge correttamente danni al target selezionato',
    ],
  },
  {
    version: '1.1.0',
    date: '2025-06-20',
    changes: [
      'Refactor: eliminato store.ts monolitico (6352 righe), ora si usa store/index.ts con 14 slices modulari',
      'La migrazione risolve definitivamente i bug di targeting delle abilità speciali (le slices avevano già resolveSpecialId corretto)',
      'Zero breaking changes: tutti i 29 componenti continuano a importare da @/game/store senza modifiche',
      'Slices: core, exploration, combat, inventory, achievements, settings, puzzle, qte, documents, npc, events, safe-room, save, debug',
    ],
  },
  {
    version: '1.1.1',
    date: '2025-06-20',
    changes: [
      'Fix struttura: eliminata cartella duplicata src/app/api/api/ (57 route.ts identici a src/app/api/)',
      'Rimossi route fantasma /api/api/* che non venivano utilizzati',
    ],
  },
  {
    version: '1.1.2',
    date: '2025-06-20',
    changes: [
      'Fix advanceToNextActor: assignment to constant variable afterEnemyAttack — destrutturazione corretta con let',
    ],
  },
  {
    version: '1.1.3',
    date: '2025-06-20',
    changes: [
      'Fix combat slice: notifId non definito — sostituito con nextNotifId() da helpers',
    ],
  },
  {
    version: '1.2.0',
    date: '2025-06-20',
    changes: [
      'Fix anti-spam esplora: aggiunto flag isExploring che impedisce click multipli durante l\'elaborazione — previene race condition (combat + evento dinamico sovrapposti)',
      'Fix eventi dinamici: aggiunto disabled a tutti i tasti azione + opzioni viaggio quando evento attivo (non solo pointer-events-none CSS)',
      'Fix combat: pannello oggetti spostato più a sinistra (right 220px) per non sovrapporre il pannello azioni su desktop',
      'Fix notifId: sostituito con nextNotifId() in events.ts e npc.ts (ultimi residui del vecchio store.ts)',
      'Il selettore quantità per trasferimento oggetti era già implementato (ammo/healing/antidote con qty > 1)',
    ],
  },
  {
    version: '1.3.0',
    date: '2025-06-20',
    changes: [
      'Audit completo: corretti 24 bug su tutto il codebase (6 critici, 8 alti, 7 medi, 3 bassi)',
      '[CRITICO] Fix save/load: aggiunti bestiary, achievements, autoCombat, dataVersion, searchedSafeRooms a tutte le 3 funzioni di salvataggio e loadGame',
      '[CRITICO] Fix saveGameVictory: aggiunti nemesisPursuitLevel, nemesisLastSeen/Location, bossPhases, lastAutoSaveTurn + size guard per randomizedLocationData',
      '[CRITICO] Fix closePuzzle: ora marca come completato solo se il puzzle è stato risolto — chiusura senza risoluzione non blocca più il puzzle',
      '[CRITICO] Fix startNewGamePlus: aggiunti reset per skipNextEncounter, nemesis*, bossPhases, debugOpen, godMode, autoCombat, randomizer*, ecc.',
      '[CRITICO] Fix ExplorationScreen: null guard su location spostato prima dell\'accesso alle proprietà',
      '[CRITICO] Fix loadGame: aggiunti searchedSafeRooms, skipNextEncounter, godMode, debugOpen, dataVersion, settingsOpen',
      '[ALTO] Fix goToCharacterSelect: aggiunto reset completo di tutti i campi GameState',
      '[ALTO] Fix GameNotification: ternario no-op corretto — label ora mostrato nel messaggio; particelle useMemo per evitare jitter',
      '[ALTO] Fix InventoryPanel: guardia null per selectedChar quando party è vuoto',
      '[ALTO] Fix SafeRoomPanel: h-screen → h-dvh sm:h-screen per viewport mobile',
      '[ALTO] Fix qte.ts: rimpiazzata mutazione diretta dello stato con set(); rimossi import inutilizzati',
      '[ALTO] Fix combat engine: clonazione activeEffects prima di handleDealDamage per evitare mutazione scudi; miss logga undefined invece di 0',
      '[MEDIO] Fix buildStartState: merge con getDefaultState() per garantire tutti i campi presenti',
      '[MEDIO] Fix determineEnding: aggiunto fallback se ending_escape non esiste',
      '[MEDIO] Fix ExplorationScreen: rimossi sottoscrizioni store inutilizzate (startQTE, encounterNpc); SafeRoomPanel in AnimatePresence; partyAvatarData in useMemo',
      '[MEDIO] Fix CombatScreen: useCallback per getAnimForTarget con useRef stabile',
      '[MEDIO] Fix NPCDialogPanel: setTimeout con cleanup mountedRef per prevenire side-effect dopo unmount',
      '[BASSO] Cleanup: rimosso NemesisInvasionState (dead code), parametro action inutile in playNemesisAttack',
    ],
  },
  {
    version: '1.4.0',
    date: '2025-06-21',
    changes: [
      'Secondo audit completo: corretti 18 bug su store, engine, UI e backend (3 critici, 3 alti, 5 medi, 7 bassi)',
      '[CRITICO] Fix explore(): aggiunta guardia null su location — previene crash se currentLocationId non valido',
      '[CRITICO] Fix travelTo(): aggiunta guardia null su currentLocation + optional chaining su lockedLocations',
      '[CRITICO] Fix searchArea(): aggiunta guardia null su location',
      '[ALTO] Fix handleHeal: cure percentuali ora usano getCharacterMaxHp() invece di p.maxHp — include bonus equipaggiamento',
      '[ALTO] Fix admin/enemy-abilities: rimosso campi inesistenti (statusType/Chance/Duration), aggiunto effects field',
      '[ALTO] Fix admin/seed-all: aggiunto header x-admin-key alle fetch interne — i seed ora funzionano correttamente',
      '[MEDIO] Fix upload routes: usano safeErrorResponse() invece di String(error) — non leakano più stack trace',
      '[MEDIO] Fix npc-chat: system prompt inviato con role system invece di assistant — protezione migliore da injection',
      '[MEDIO] Fix unlockAchievement: clearTimeout prima di settare nuovo timer — previene race condition su notifiche',
      '[MEDIO] Fix restartGame(): aggiunto isExploring: false al reset',
      '[MEDIO] Fix boss phase check: guardia divisione per zero se enemy.maxHp <= 0',
      '[BASSO] Fix debugKillAllEnemies: chiama advanceToNextActor() invece di executeCombatTurn() — vittoria ora innesca',
      '[BASSO] Cleanup engine/combat.ts: rimossi import inutilizzati (CombatState, EffectTarget, ItemDefinition)',
      '[BASSO] Cleanup bgm.ts: rimosso type BgmType duplicato — usa quello importato da sounds.ts',
      '[BASSO] Fix Rarity type: aggiunto epic al type union — corrisponde alle lookup tables in rarity-helpers.ts',
    ],
  },
  {
    version: '1.5.0',
    date: '2025-06-21',
    changes: [
      'Fix suoni: aggiunto setValueAtTime prima di linearRampToValueAtTime in _suspendAmbient e _resumeAmbient — l\'ambient ora si ferma correttamente durante il combat',
      'Fix suoni: rimosso preload dei suoni — ora i suoni si sentono solo se caricati nel DB, nessun 404 silenzioso',
      'Fix suoni: eliminato bgm.ts (codice morto con procedural BGM che non veniva usato)',
      'Fix missioni: encounterNpc() non filtra più le quest in-progress — le missione fetch/explore sono ora completabili',
      'Rimosso pannello badge dinamico compatto sopra i tasti azione',
      'Rimosso spinner \'[npc] sta parlando...\' e fake delay 400ms dal dialogo NPC — dialogo ora istantaneo con frasi statiche',
      'Rimosso label \'risposta predefinita\' da tutti i messaggi NPC',
      'Eliminata route API /api/npc-chat (213 righe di codice AI mai usata)',
    ],
  },
  {
    version: '1.5.1',
    date: '2025-06-21',
    changes: [
      '[CRITICO] Fix NPCDialogPanel: errore di build "const declarations must be initialized" — mancavano le parentesi [] nella destrutturazione di useState (regressione da v1.5.0)',
      '[CRITICO] Fix consegna missioni: handleTalk() ritornava prematuramente se l\'NPC non aveva dialogues — talkToNpc() non veniva mai chiamato e le quest fetch non si completavano',
      '[ALTO] Fix suono zombie: rimosso timer periodico playZombieMoan ogni 4-8s in combat — i suoni zombie ora si sentono solo quando lo zombie attacca (via getSoundForEntry)',
      '[ALTO] talkToNpc() ora restituisce { handled, chatMessage } — il dialogo NPC mostra il messaggio corretto (consegna, stato missione o frase casuale)',
      '[MEDIO] Rimosso notification overlay per eventi dinamici — l\'evento appare solo nel Registro Eventi senza popup',
      '[BASSO] Cleanup: rimosso campo isFallback inutilizzato da ChatMessage',
    ],
  },
  {
    version: '1.6.0',
    date: '2025-06-22',
    changes: [
      '[NUOVO] Sistema Victory Conditions: 5 sfide bonus EXP attivate nel combat loop (sopravvivi turni, distruggi punto debole, elimina bersaglio)',
      '[NUOVO] Sistema Combo Chain: combo counter progressivo per attacchi consecutivi sullo stesso bersaglio — da +10% (x2) a +50% (x8+) danno bonus',
      '[NUOVO] 3 Stanze Segrete: Armeria RPD (document), Bunker Fogne (search 15%), Lab Birkin (NPC hint) con loot esclusivo (magnum, zaino, lanciarazzi)',
      '[NUOVO] 2 Eventi Dinamici: Invasione Nemesis (minTurn 15, +130% enemy stats) e Ondata Zombie (minTurn 8, +40% encounter rate)',
      '[NUOVO] 6 Ricette Crafting: adrenalina, pillola difensiva, bomba artigianale, spray super, munizioni mitragliatrice, mega benda',
      '[NUOVO] 3 Nuovi Oggetti: Iniezione Adrenalina (+20 ATK), Pillola Difensiva (+15 DEF), Bomba Artigianale (50 dmg AoE)',
      '[UI] Combo counter badge in CombatHeader con animazione pulse a x5+',
      '[UI] Sfida bonus Victory Condition mostrata in CombatHeader durante il combat',
      '[REFATTORI] Victory conditions: rimosso avviso "DEAD CODE", importato nel combat loop',
      '[REFATTORI] DynamicEventType: aggiunti nemesis_invasion e horde al type union',
    ],
  },
  {
    version: '1.7.0',
    date: '2025-06-22',
    changes: [
      '[NUOVO] Sistema Ricette Scopribili: 9 ricette nascoste che si sbloccano esplorando — 6 ricette base sempre visibili',
      '[NUOVO] Discovery tramite documenti: 3 documenti (diario RPD, report lab, mappa fogne) sbloccano ricette segrete',
      '[NUOVO] Discovery randomica: 8% di probabilità per search di scoprire una ricetta nascosta',
      '[UI] Contatore ricette scoperte (es. 8/15) nei pannelli Crafting e Inventario',
      '[UI] Placeholder misteriosi "???" per ricette non ancora scoperte con icona lucchetto',
      '[PERSISTENZA] discoveredRecipes salvato/caricato in tutti gli slot + autosave + NG+',
      '[SISTEMA] CraftingRecipe.hidden field + discoverRecipe() action nel GameStore',
    ],
  },
  {
    version: '1.8.0',
    date: '2025-06-22',
    changes: [
      '[CRITICO] Fix 3 Stanze Segrete inaccessibili: RPD Armory (doc fantasma → doc_chief_diary), Lab Birkin (locationId errato → laboratory_entrance), Lab Birkin (quest fantasma → quest_voss_data creata per Dr. Voss)',
      '[CRITICO] Fix 3 Documenti fantasma per recipe discovery: creati doc_rpd_diary, doc_lab_report, doc_sewers_map con lore RE — ora 9 ricette nascoste sono scopribili tramite documenti',
      '[CRITICO] Fix 3 Achievement impossibili: "Combattimento Perfetto" (checkPerfectCombat), "Erborista" (herbCombineCount tracking), "Comando Automatico" (checkAutoCombatVictory su vittoria)',
      '[CRITICO] Fix Pipe Bomb: aggiunto flat/amount a DealDamageEffect + logica flat damage nel combat engine — ora infligge 50 danni fissi instead of ATK-based',
      '[ALTO] Fix Ending "Eroe": ora conta NPC con quest completate (npcQuestProgress.completed) invece di NPC incontrati (npcsEncountered)',
      '[ALTO] Fix Flashlight/Lockpick: impostato usable=false — non più consumabili senza effetto',
      '[ALTO] Fix Achievement Bestiary: contatore aggiornato da 12 a 13 nemici (include proto_tyrant)',
      '[ALTO] Aggiunto isExploring: boolean al tipo GameState + herbCombineCount: number per tracking achievement',
      '[MEDIO] Rimosso codice morto: useAIContentGenerator.ts, secrets.ts, dynamic-events.ts (3 file)',
      '[MEDIO] Fix softlock key_rpd: aggiunto al pool item city_outskirts (8% chance) oltre a hospital (12%)',
      '[MEDIO] Aggiunto campo hidden Boolean @default(false) a Prisma GameRecipe',
      '[MEDIO] Aggiunto quest_voss_data "Dati del Progetto Tyrant" al Dr. Voss — Sconfiggi 2 Hunter per sbloccare hint stanza segreta',
      '[MEDIO] Dr. Chen: aggiunto questCompletedDialogue per messaggio post-quest',
      '[NUOVO] 3 Documenti segreti: Diario Irons (RPD), Report Armi Improvvisate (Lab), Mappa Condotti C-7 (Fogne)',
      '[PERSISTENZA] herbCombineCount salvato/caricato in tutti gli slot save + autosave + NG+',
    ],
  },
  {
    version: '1.13.0',
    date: '2025-06-27',
    changes: [
      '[NUOVO] Quinto Archetipo "Survivor": Sofia Reyes — ibrido supporto/combatente che mantiene in vita il gruppo',
      '[NUOVO] Abilità Speciale "Soccorso Rapido": cura 40 HP al compagno più ferito, rimuove status negativi e buffa difesa (CD: 12 turni)',
      '[NUOVO] Abilità Speciale "Segnalazione Emergenza": potenzia ATK e SPD per 3 turni + applica adrenalina (CD: 18 turni)',
      '[NUOVO] Passive "Adattabilità": +10% efficacia a tutti gli oggetti curativi e abilità di cura usati dal Survivor',
      '[SISTEMA] Archetype type aggiornato: aggiunto "survivor" alla union type',
      '[SISTEMA] 2 nuove abilità speciali nel pool: soccorso_rapido, segnalazione_emergenza (support category)',
      '[UI] CharacterSelect: colori ciano per il Survivor, icona scudo, mappature bordo/glow/label aggiornate',
      '[CONTENUTO] Equipaggiamento iniziale: coltello, 2 bende, erba verde, torcia, giravite',
      '[BACKWARD COMPAT] I 4 archetipi esistenti completamente invariati',
    ],
  },
  {
    version: '1.14.0',
    date: '2025-06-27',
    changes: [
      '[NUOVO] Timeline Turni Combattimento: barra orizzontale visibile in CombatHeader che mostra ordine turni (giocatori + nemici) basato su velocità',
      '[NUOVO] Tooltip migliorati: tooltip info su attacchi (arma + mod installati), abilità speciali (descrizione + cooldown + categoria), difesa, oggetti, fuga',
      '[NUOVO] Combat Log migliorato: icone tipo per ogni voce (💥 danno, 💚 cura, ☠️ veleno, 🩸 sanguinamento, ⚡ stordito), codice colori per categoria (rosso danno, verde cura, viola veleno, arancio adrenalina, viola proc)',
      '[NUOVO] Filtri Combat Log: pulsanti "Tutto/Danno/Cura/Stato/Proc" per filtrare le voci del registro',
      '[NUOVO] Separatori Turni: linee visive "─── Turno N ───" tra i turni nel combat log',
      '[NUOVO] Auto-scroll intelligente: il log non scrolla automaticamente se l\'utente ha scrollato verso l\'alto, con pulsante "↓ Ultimo" per tornare in fondo',
      '[NUOVO] Screen shake migliorato: tre livelli di intensità — normale (critici), pesante (>50 dmg), pesantissimo (morte nemico)',
      '[NUOVO] Flash verde cure: evidenziazione verde sulla scheda del personaggio quando riceve cure',
      '[NUOVO] Badge Stato Visivi: indicatori animati per veleno (bordo viola pulsante), sanguinamento (bordo rosso), stordito (bordo giallo flash), adrenalina (bordo arancio glow) con durata residua',
      '[NUOVO] Numeri Fluttuanti: danni e cure appaiono come numeri animati fluttuanti sopra i personaggi (rosso danno, verde cure, giallo critici)',
      '[NUOVO] Tooltip scheda Personaggio: hover per vedere breakdown statistiche (ATT/DIF/VEL base + equipaggiamento + buff attivi)',
      '[UI] CombatHeader espanso con barra turni orizzontale compatto per desktop e mobile',
      '[UI] Status badge CSS con animazioni tematiche per ogni effetto di stato',
    ],
  },
  {
    version: '1.14.0',
    date: '2025-06-28',
    changes: [
      '[NUOVO] Sistema Statistiche Run: tracciamento dettagliato di 22 metriche durante la partita (danni, nemici, esplorazione, crafting, tempo, ecc.)',
      '[NUOVO] Schermata Statistiche post-vittoria: 4 sezioni (Combattimento, Esplorazione, Crafting, Tempo/Progressione) con icone e layout a griglia',
      '[NUOVO] Classifica Locale (Leaderboard): classifica top 10 run in localStorage con punteggio calcolato basato su combattimento, esplorazione, velocità, NG+, finali e achievement',
      '[NUOVO] Tracker Achievement Completo: griglia visiva con filtri per categoria (Tutti, Combattimento, Esplorazione, Raccolta, Storia, Speciale), barra progresso, traguardi nascosti',
      '[NUOVO] Score System: punteggio composito basato su +50/nemico, +200/boss, +100/stanza segreta, +50/documento, -1/turno (velocità), +500/ciclo NG+, bonus finali',
      '[SISTEMA] RunStats interface con 22 campi tracciati in tempo reale',
      '[SISTEMA] incrementRunStat(key, value) action nel GameStore per tracciamento leggero delle statistiche',
      '[SISTEMA] _trackCombatVictoryStats() per analisi post-combat (danni, kill, combo, perfect combat)',
      '[SISTEMA] Leaderboard utility (calculateScore, getLeaderboard, addLeaderboardEntry, formatPlayTime)',
      '[UI] VictoryScreen riscritto con 3 tab navigabili: Statistiche 📊, Classifica 🏆, Traguardi ⭐',
      '[UI] Badge punteggio e tempo di gioco nel header della schermata vittoria',
      '[PERSISTENZA] runStats salvato/caricato in saveGame, autoSave, loadGame, saveGameVictory, startNewGamePlus',
      '[PERSISTENZA] Leaderboard salvata in localStorage (max 50 entry)',
    ],
  },
  {
    version: '1.15.0',
    date: '2025-06-28',
    changes: [
      '[NUOVO] Timeline Turni Combattimento: barra orizzontale in CombatHeader che mostra ordine turni (giocatori + nemici) basato su velocità, con evidenziazione attore corrente',
      '[NUOVO] Combat Log migliorato: icone tipo per ogni voce (💥 danno, 💚 cura, ☠️ veleno, 🩸 sanguinamento, ⚡ stordito, 🛡️ difesa, 💊 adrenalina)',
      '[NUOVO] Filtri Combat Log: pulsanti "Tutto/Danno/Cura/Stato" per filtrare le voci del registro di combattimento',
      '[NUOVO] Separatori Turni: linee visive "─── Turno N ───" tra i turni nel combat log per leggibilità migliorata',
      '[NUOVO] Auto-scroll intelligente: il log non scrolla se l\'utente ha scrollato verso l\'alto, con pulsante "↓" per tornare in fondo',
      '[UI] Status Badge CSS: animazioni tematiche per veleno (bordo viola pulsante), sanguinamento (bordo rosso), stordito (bordo giallo), adrenalina (bordo arancio glow)',
      '[UI] Numeri fluttuanti migliorati: animazione CSS dedicata con scale-up e fade-out, dimensione aumentata per critici',
      '[UI] Heal Flash verde: bordo + glow verde sulla scheda personaggio quando riceve cure',
      '[CSS] Floating combat number classes (combat-float-number, combat-float-up, combat-float-crit)',
      '[CSS] Status badge classes (status-badge, status-badge-poison/bleeding/stunned/adrenaline) con animazioni pulsanti',
      '[CSS] Turn order timeline classes (turn-order-timeline, turn-order-entry, turn-order-arrow)',
      '[CSS] Combat log filter and separator classes (combat-log-filter-btn, combat-log-separator, scroll-to-bottom-btn)',
      '[TIPI] TurnOrderEntry interface aggiunta a types.ts',
    ],
  },
  {
    version: '1.16.0',
    date: '2025-06-28',
    changes: [
      '[NUOVO] Crafting Quality System: qualità randomica (Normale 70%, Qualità Superiore 25% ⭐, Qualità Maestra 5% ⭐⭐) su tutti gli oggetti craftati',
      '[NUOVO] Item Breakdown (Smonta Oggetto): smonta oggetti dall\'inventario per ottenere Punti Craft (Common=1, Uncommon=2, Rare=3, Epic=5, Legendary=8)',
      '[NUOVO] Point-Based Crafting: ogni ricetta ha un costo in Punti Craft (facile=3, medio=5, difficile=8), pagabile come alternativa agli ingredienti',
      '[NUOVO] 3 Ricette Solo Punti: Munizioni Biohazard (12pt → 6 granate), Campionamento Virale (15pt → 1 lanciarazzi), Spray Ultimato (10pt → 1 spray maestra)',
      '[NUOVO] Punti Craft: saldo visibile nel pannello Crafting, ottenuto smontando oggetti e speso per craftare',
      '[SISTEMA] ItemQuality type + quality field su ItemInstance',
      '[SISTEMA] QUALITY_LABELS + RARITY_POINTS exports da data/crafting.ts',
      '[SISTEMA] CraftingRecipe esteso con pointCost, pointOnly, ngPlusOnly, forceMasterQuality',
      '[SISTEMA] craftItemWithPoints() e breakdownItem() actions nel GameStore',
      '[SISTEMA] Tracciamento totalCrafted e masterQualityCrafted in GameState',
      '[ACHIEVEMENT] Maestro Artigiano: crea 20 oggetti tramite crafting',
      '[ACHIEVEMENT] Artigiano Perfetto (nascosto): crea 3 oggetti di Qualità Maestra',
      '[UI] Tab "Smonta" nel pannello Crafting con lista oggetti smontabili per personaggio e punti previsti',
      '[UI] Badge qualità (⭐/⭐⭐) su log messaggi di crafting',
      '[DB] Schema GameRecipe: aggiunti campi pointCost, pointOnly, ngPlusOnly, forceMasterQuality',
      '[SEED] 3 nuove ricette solo punti + pointCost su tutte le 15 ricette esistenti',
      '[PERSISTENZA] craftingPoints, totalCrafted, masterQualityCrafted salvati in tutti gli slot',
      '[TIPI] RunStats, QuestChainProgress, PermanentEffect interfaces in types.ts',
    ],
  },
  {
    version: '1.17.0',
    date: '2025-06-29',
    changes: [
      '[CRITICO] Fix CraftingPanel: proprietà `qty` non esistente → corretto in `quantity` — ingredienti ora mostrano correttamente disponibilità e quantità',
      '[CRITICO] Fix CraftingPanel: ricette solo-punti mostravano "Pronto" verde anche con 0 punti — `canCraft` ora false per pointOnly',
      '[CRITICO] Fix _trackCombatVictoryStats: funzione mai chiamata dopo vittoria — tutte le statistiche combat (danni, kill, combo) erano sempre a 0',
      '[CRITICO] Fix runStats undefined dopo caricamento save vecchi — crash su incrementRunStat() se runStats mancava',
      '[CRITICO] Fix restartGame(): runStats non veniva resettato — statistiche della run precedente persistevano',
      '[CRITICO] Fix Nemesis fuga: fuggire al livello 4 poneva pursuitLevel a 5 = sconfitta permanente — ora capped a 4',
      '[ALTO] Fix Victory Condition destroy_weak_point: bonus EXP sempre assegnato ignorando limite turni — ora controlla turnsRequired',
      '[ALTO] Fix 6 statistiche run mai tracciate: turnsSurvived, searchesPerformed, distanceTraveled, documentsFound, dynamicEventsSurvived, itemsUsed — ora tracciate',
      '[ALTO] Fix Combo damage non contato nelle statistiche: aggiunto campo `damage` al log entry combo',
      '[ALTO] Fix VictoryScreen: useMemo usato per side effect (setState) — corretto in useEffect',
      '[MEDIO] Fix label Nemesis Livello 5: mostrava "Rabbia Estrema" invece di "Sconfitto" — aggiunto caso separato',
      '[MEDIO] Fix Nemesis combat `fled: true` hardcoded all\'inizio — impostato a `false`, semantica corretta',
      '[MEDIO] Fix descrizione ricetta Campionamento Virale: ora menziona Punti Craft invece di "materiali di laboratorio"',
      '[MEDIO] Fix descrizione ricetta Siero del Tyrant: rimossa promessa di doppio risultato (produce solo Adrenalina)',
      '[MEDIO] Fix initial-state.ts: import mancanti per QuestChainProgress e PermanentEffect — `as` assertions silenti rimosse',
      '[MEDIO] Fix leaderboard.ts: turnsSurvived fallback a 0 se mancante — penalità velocità non crasha più',
    ],
  },
  {
    version: '1.18.0',
    date: '2025-07-01',
    changes: [
      '[NUOVO] Tab unificate "Location & Mappa": le tab Location e Mappa Visuale sono state unite in un\'unica tab con gestione completa CRUD + posizionamento visuale',
      '[NUOVO] Pulsante "Aggiungi Location" dalla mappa: apre il dialog di creazione con tutti i campi, senza cambiare tab',
      '[NUOVO] Pulsanti modifica/elimina su ogni cella della griglia (visibili su hover) e nella sidebar',
      '[NUOVO] Nomi delle location collegate mostrati sotto ogni nodo sulla mappa (toggle 🏷️)',
      '[NUOVO] Frecce direzionali per collegamenti adiacenti sulla griglia (toggle ↗️)',
      '[NUOVO] Batch positions API: salvataggio atomico di tutte le posizioni in una singola transazione',
      '[FIX] Fix errore salvataggio mappa: sostituite N richieste PUT concorrenti con singola batch transaction',
      '[UX] Connection names con indicatori: collegamenti bloccati mostrati in ambra con icona 🔒',
      '[UX] Sidebar non posizionate mostra collegamenti per aiutare il posizionamento',
    ],
  },
  {
    version: '1.19.0',
    date: '2026-04-23',
    changes: [
      '[FIX] Pulsante Seed Default ripristinato nel MapEditor — era sparito dopo l\'unione delle tab Location + Mappa',
      '[FIX] Campi location vuoti nell\'edit: enemyPool, itemPool, description, encounterRate e tutti gli altri campi ora popolati correttamente dal DB',
      '[FIX] mapCol e mapRow rimossi dal modale location — gestiti visivamente tramite drag-and-drop sulla griglia',
      '[FIX] Seed API: mapDanger tipo corretto (Int non String), risposta API con message, campi mancanti aggiunti',
      '[FIX] Creazione location: coercione numeri e gestione mapDanger auto nel POST handler',
      '[FIX] Dropdown autocomplete pool oggetti: rimosso overflow-hidden che tagliava il dropdown nelle tabelle',
      '[UX] Banner descrittivo delle location sotto l\'header del MapEditor',
      '[UX] Dropdown oggetti mostra tutti i risultati quando il campo è vuoto',
      '[UX] Pulsanti modifica/elimina ingranditi con testo, sempre visibili sulle card location',
      '[ADMIN] Aggiunto archetipo survivor, rarità epic, event types nemesis_invasion/horde',
      '[ADMIN] Campi NPC badge (label, icon, color) ora visibili e modificabili',
      '[ADMIN] Campi recipe avanzati (pointCost, pointOnly, ngPlusOnly, forceMasterQuality, hidden) ora visibili',
      '[ADMIN] Fix API routes (events, quests, documents, recipes): serializzazione JSON corretta per campi String',
      '[ADMIN] Fix Characters PUT: coercione numeri per campi stat',
      '[ADMIN] Fix MapEditor: campi nullable ora impostati a null invece che eliminati',
    ],
  },
  {
    version: '1.20.0',
    date: '2026-04-24',
    changes: [
      '[CRITICO] Fix run-stats slice non montato nello store — incrementRunStat e _trackCombatVictoryStats ora funzionano correttamente',
      '[NUOVO] Feature #2 — Missioni Multi-Step con Branching: 3 catene di missioni (Sangue Infetto, Ombre nel Cimitero, Il Traditore) con passaggi fetch/kill/explore/talk/choose',
      '[NUOVO] Feature #2 — Scelte di ramo: le missioni offrono scelte che influenziano la storia e le ricompense (flags tracciati)',
      '[NUOVO] Feature #2 — Slice quest-chains.ts: acceptQuestChain, advanceQuestChainStep, handleChainBranchChoice, getActiveChainForNpc',
      '[NUOVO] Feature #3 — Sistema Reputazione NPC: punteggio per ogni NPC che sale completando missioni (+2)',
      '[NUOVO] Feature #3 — Badge reputazione: Neutrale (0), Amichevole (1-3), Affidato (4-6), Alleato (7+), Sospettoso (-2)',
      '[NUOVO] Feature #3 — Saluti dinamici basati su reputazione: "Vecchio amico" (7+), "Buon amico" (4+)',
      '[NUOVO] Feature #3 — Sconto commercio: -1 prezzo a 4+ reputazione, -2 a 7+ reputazione',
      '[NUOVO] Feature #4 — New Game+ Avanzato: moltiplicatore nemici per ciclo (1.15x/1.30x/1.50x)',
      '[NUOVO] Feature #4 — Crafting points parziali: 30% dei punti craft vengono portati nel NG+',
      '[NUOVO] Feature #4 — Bonus oggetti NG+ Ciclo 2+: Antidoto x2 all\'inizio',
      '[NUOVO] Feature #4 — 3 Achievement NG+: Nuovo Inizio (1 ciclo), Veterano (3 cicli), Leggenda (5 cicli, nascosto)',
      '[NUOVO] Feature #5 — Eventi Dinamici a Catena: 3 sequenze (blackout→aftermath, gas→spread, fire→secondary)',
      '[NUOVO] Feature #5 — Eventi concatenati con scheduling: se il turno non è sufficiente, l\'evento viene programmato',
      '[NUOVO] Feature #5 — Indicatore ⛓️ nella UI per eventi a catena',
      '[TIPI] MultiStepQuest, QuestChainStep, QuestChainProgress (con currentStepIndex + chosenFlags)',
      '[TIPI] DynamicEvent.chainId, nextEventId, permanentMapEffect',
      '[TIPI] GameState.npcReputation, ngPlusEnemyMultiplier, completedChains',
      '[SISTEMA] 16 slice nello store (aggiunti run-stats + quest-chains)',
    ],
  },
  {
    version: '1.21.0',
    date: '2026-04-24',
    changes: [
      '[DB] Tutte le feature v1.20.0 ora pienamente configurabili da database — zero hardcoded values',
      '[DB] Nuovo modello QuestChain + QuestChainStep + QuestChainFinalReward nel DB (3 tabelle)',
      '[DB] DynamicEvent: aggiunti campi chainId, nextEventId, permanentMapEffect',
      '[DB] GameNPC: aggiunto campo dynamicDialogues per dialoghi condizionali',
      '[API] CRUD completo per Quest Chains (GET/POST/PUT/DELETE) in /api/admin/quest-chains',
      '[API] Seed endpoint per popolare le 3 catene di missione esistenti nel DB',
      '[LOADER] Quest chains caricate dal DB tramite QUEST_CHAINS_DATA + NPC_QUEST_CHAIN_MAP',
      '[LOADER] Aggiunto REPUTATION_CONFIG e NGPLUS_CONFIG — valori da GameSetting DB',
      '[STORE] quest-chains.ts: usa QUEST_CHAINS_DATA dal DB invece di SEED_QUEST_CHAINS hardcoded',
      '[STORE] npc.ts: sconto reputazione configurabile via REPUTATION_CONFIG (thresholds + amounts)',
      '[STORE] core.ts: NG+ moltiplicatore e bonus oggetti configurabili via NGPLUS_CONFIG',
      '[STORE] save.ts: NG+ craft points % portati configurabile via NGPLUS_CONFIG',
      '[ADMIN] Tab "Missioni Chain" nel pannello admin con editor visuale steps + branching',
      '[ADMIN] Campi chainId, nextEventId, permanentMapEffect nella tab Eventi',
      '[ADMIN] Campo dynamicDialogues nella tab NPC per dialoghi condizionali',
      '[CONFIG] reputation.* e ngplus.* settings in GameSetting per tutti i valori configurabili',
    ],
  },
  {
    version: '1.21.1',
    date: '2026-04-24',
    changes: [
      '[FIX] Fix MediaUploadsSection: aggiunto null guard su mediaUploads — previene crash quando il prop è undefined',
      '[FIX] Quest Chain steps vuoti nell\'editor: GET /api/admin/quest-chains ora include steps + finalReward con JSON parsato',
      '[FIX] Ricompensa Finale: da textarea JSON grezza a editor visuale con campi dedicati (EXP, items, dialoghi)',
      '[FIX] Dialoghi Dinamici NPC: da textarea JSON a editor visuale con card collassabili, conditions (type/compare/value), priorità',
      '[FIX] Effetto Permanente Mappa: da textarea JSON a editor visuale con type select, locationId, value con auto-type detection',
      '[FIX] NPC API: dynamicDialogues ora incluso in GET/POST/PUT (era completamente mancante)',
      '[FIX] Events API: permanentMapEffect serializzato con jsonStr() in POST/PUT',
      '[ADMIN] Nuovo editor DynamicDialoguesEditor (tema viola) per dialoghi condizionali NPC',
      '[ADMIN] Nuovo editor PermanentMapEffectEditor (tema arancio) per effetti permanenti mappa',
      '[ADMIN] QuestChainFinalRewardEditor ora collegato (esisteva ma non era usato)',
      '[ADMIN] Campo "Prossimo Evento" ora usa entity-search con ricerca su eventi esistenti (titolo + icona)',
      '[IMPOSTAZIONI] Nuova sezione 🔄 New Game+ con 7 campi (moltiplicatori, craft points %, bonus item)',
      '[IMPOSTAZIONI] Nuova sezione 💬 Reputazione NPC con 6 campi (soglie sconto, rep per quest, soglia sospetto)',
    ],
  },
  {
    version: '1.21.2',
    date: '2026-04-24',
    changes: [
      '[FIX] Quest Chain Steps: targetId da testo libero a Entity Search dinamico (fetch→items, kill→nemici, explore→locations, talk→NPCs)',
      '[FIX] Quest Chain Steps: rewardItems da JSON raw a editor visuale con MiniEntitySearch e tabella strutturata',
      '[FIX] Quest Chain Steps: rewardDialogue mancante nell\'editor visuale — aggiunto editor con righe editabili singole',
      '[FIX] Quest Chain Steps: nextStepId da testo libero a dropdown select popolato con gli step della catena',
      '[FIX] Quest Chain Steps: branch nextStepId da testo libero a dropdown select',
      '[FIX] Quest Chain Steps: campi non necessari nascosti per tipo step (targetId/targetCount per choose, targetCount per talk/explore)',
      '[UX] Aggiunti tooltip esplicativi a tutti i campi degli steps (Step ID, Tipo, Target, Count, Descrizione, Next Step, Rewards, Branching, Flag)',
      '[UX] Aggiunti tooltip alla Ricompensa Finale e a tutti i suoi campi (EXP, Items, Dialoghi)',
      '[UX] Banner informativi per comportamento specifico per tipo step (explore/talk ignorano targetCount, choose non usa target)',
      '[UX] Items Ricompensa Finale: da JSON raw a editor visuale con MiniEntitySearch',
      '[FIX] Tooltip Quest Chain: sostituiti componenti Radix Tooltip (non funzionanti) con attributo title HTML nativo — ora i tooltip (?) appaiono correttamente',
    ],
  },
  {
    version: '1.21.3',
    date: '2026-04-24',
    changes: [
      '[UX] Tooltip stilizzati: sostituiti tutti i tooltip nativi HTML title con AdminTooltip — bubble visuale con sfondo scuro, bordo, freccia e animazione fade-in',
      '[UX] AdminTooltip: componente riutilizzabile con supporto posizioni (top/bottom/left/right), icona Info o testo (?), dimensioni sm/md',
      '[UX] Tooltip applicati a tutto il pannello admin: FieldWrapper, FieldContainer (EntityForm), QuestChainsEditor, EffectsArrayEditor, StatusEditors, MediaUploadBox',
      '[FIX] Tooltip ora funzionano correttamente dentro container con overflow (scroll) grazie al posizionamento assoluto CSS puro senza portal Radix',
    ],
  },
  {
    version: '1.21.4',
    date: '2026-04-24',
    changes: [
      '[FIX] AdminTooltip: riscritto con React Portal — il tooltip viene renderizzato nel document.body e non viene più tagliato dai container con overflow:hidden/auto',
      '[FIX] AdminTooltip: risolto problema z-index — tooltip sempre in primo piano (z-index: 99999) rispetto a qualsiasi contenitore',
      '[UX] AdminTooltip: larghezza aumentata da 220px a 340px per testi più leggibili',
      '[UX] AdminTooltip: aggiunta animazione fade-in con blur per apparizione più fluida',
      '[UX] AdminTooltip: padding aumentato per migliore leggibilità',
    ],
  },
  {
    version: '1.21.5',
    date: '2026-04-25',
    changes: [
      '[FIX] Upload suoni: rimosso il middleware dalle rotte upload (che imponeva il limite di 10MB) — i file audio grandi ora vengono caricati correttamente',
      '[FIX] Upload: aggiunto controllo auth diretto nelle route handler sound/image — le rotte upload rimangono protette anche senza middleware',
      '[FIX] SoundPreviewButton: aggiunto type="button" al pulsante play — senza questo, dentro un <form> il click faceva submit del form e chiudeva il dialog invece di riprodurre il suono',
      '[UX] StartScreenEditor: aggiunta sezione Media Upload con upload BGM (bgm_title) — ora è possibile caricare la musica della schermata titolo direttamente dal pannello admin',
      '[UX] StartScreenEditor: migliorato layout sezione upload sfondo — spostato dentro card con bordo, stesso stile degli altri MediaUpload',
    ],
  },
  {
    version: '1.21.6',
    date: '2026-04-25',
    changes: [
      '[CRITICO] Fix controlli volume: lo slider SFX abbassava TUTTO l\'audio (musica + effetti) perché condivideva il masterGain — ora SFX ha un GainNode dedicato e indipendente',
      '[FIX] Slider SFX ora controlla esclusivamente gli effetti sonori (attacchi, notifiche, effetti combattimento, menu)',
      '[FIX] Slider BGM ora controlla sia la musica di sottofondo che l\'ambientazione delle location (routing corretto attraverso bgmGain)',
      '[FIX] Slider Master controlla il volume generale senza interferire con SFX o BGM',
      '[AUDIO] Nuovo audio routing: masterGain → { sfxGain, bgmGain } — tre canali indipendenti',
    ],
  },
  {
    version: '1.21.7',
    date: '2026-04-25',
    changes: [
      '[CRITICO] Fix suoni nemico: gli attacchi base ("Attacco") non producevano alcun suono — combat-utils.ts restituiva null per actorType=enemy con action=Attacco',
      '[CRITICO] Fix ref key nemico: playEnemyAttack() derivava la ref key dal nome visualizzato ("Zombie Donna" → attack_zombie_donna) invece che dal definitionId (zombie_female) — la maggior parte dei suoni caricati non venivano trovati',
      '[CRITICO] Fix ref key ambient nel DB: i suoni ambient pre-seedati usavano formato vecchio (playAmbientCity) ma il motore cercava formato nuovo (ambient_city_outskirts) — aggiornati 5 record nel DB',
      '[FIX] CombatLogEntry: aggiunto campo actorDefinitionId per passare il definitionId nemico dal combat engine al sistema audio',
      '[FIX] Eliminato bgm.ts — codice morto (381 righe di BGM sintetizzato che mai veniva importato ma poteva causare confusione)',
      '[FIX] 11 log entry nel combat engine e combat store slice aggiornati con actorDefinitionId',
      '[AUDIO] I suoni attacco/morte caricati per nemici ora vengono riprodotti correttamente usando il definitionId',
      '[AUDIO] I suoni ambientali delle location ora vengono riprodotti con le ref key corrette',
    ],
  },
  {
    version: '1.21.8',
    date: '2026-04-25',
    changes: [
      '[CRITICO] Fix cache audio: l\'AudioEngine manteneva in cache i buffer decodificati — dopo un upload di un nuovo suono via admin, il vecchio suono continuava a essere riprodotto perché la cache non veniva invalidata',
      '[CRITICO] Fix doppi suoni location: durante l\'esplorazione venivano riprodotti simultaneamente BGM (sintetico dal seed) e ambient (caricato) — ora se un ambient personalizzato esiste nel DB, il BGM generico viene soppresso automaticamente',
      '[FIX] HTTP cache: fetch dei suoni ora usa cache: "no-store" — il browser non serve più versioni obsolete dei suoni caricati',
      '[FIX] API Cache-Control: cambiato da "public, max-age=3600" a "no-store" — il server non istruisce più il browser a cachare i suoni',
      '[AUDIO] invalidateSound(refKey): nuovo metodo per invalidare una specifica entry dalla cache SFX e BGM — se il suono è in riproduzione viene fermato e riavviato con il nuovo audio',
      '[AUDIO] invalidateAllSounds(): nuovo metodo per svuotare completamente tutte le cache audio',
      '[AUDIO] notifySoundUpdated(refKey): export che dispatcha un CustomEvent "sound-updated" — i componenti admin lo chiamano dopo ogni upload di successo',
      '[AUDIO] L\'AudioEngine ascolta automaticamente "sound-updated" e invalida la cache corrispondente',
      '[AUDIO] playBgm(): se un ambient personalizzato è attivo, i BGM di tipo location vengono saltati — combat/gameover/victory BGM hanno sempre priorità',
    ],
  },
  {
    version: '1.22.0',
    date: '2026-04-25',
    changes: [
      '[AUDIO] Rimozione completa di tutti i suoni sintetici/seeded — il gioco usa SOLO audio caricati dal DB tramite il pannello admin',
      '[AUDIO] Eliminati 47+ metodi play hardcoded da sounds.ts (playAttack, playMiss, playCritical, playZombieMoan, playMenuOpen, ecc.) — nessun suono pre-impostato, solo suoni entity-specific',
      '[AUDIO] Rimasti solo metodi entity-specific: playEnemyAttack, playEntityEnemyDeath, playEntitySpecial, playEntityEnemyAbility, playEntityBossPhase, playLocationAmbient',
      '[AUDIO] Sistema BGM preservato — funziona solo con audio caricati dal DB (bgm_title, bgm_combat, ecc.)',
      '[AUDIO] Sistema Cache invalidation preservato (invalidateSound, notifySoundUpdated)',
      '[SEED] Rimosso array SOUND_SEEDS (52 definizioni) dal seed route — il seed ora cancella solo i record sound esistenti senza ricrearli',
      '[COMBAT] combat-utils.ts: getSoundForEntry() ora restituisce null per azioni senza suono entity-specific — nessun fallback hardcoded',
      '[COMBAT] useCombatAnimations.ts: rimosso import playEnemyDeath (generico) — usa solo audio.playEntityEnemyDeath con definitionId',
      '[UI] GameNotification: rimosso import audio e tutti i suoni hardcoded (encounter, victory, defeat, item_found)',
      '[STORE] Rimossi ~28 try/catch blocks con play*() da 10 store slices (achievements, events, puzzle, inventory, safe-room, npc, documents, settings, exploration, combat)',
      '[STORE] exploration.ts: import ridotto a solo playLocationAmbient (rimossi 8 altri suoni importati)',
      '[STORE] combat.ts: import ridotto a solo audio (rimossi playLevelUp, playVictory, playDefeat)',
    ],
  },
  {
    version: '1.22.1',
    date: '2026-04-25',
    changes: [
      '[CRITICO] Fix doppio audio location: playBgm() veniva chiamato anche durante l\'esplorazione sovraponendosi a playLocationAmbient() — ora playBgm() si usa SOLO per stati non-location (title, combat, gameover, victory)',
      '[AUDIO] Rimossi 6 location entries da BGM_REF_KEYS (city_outskirts, rpd_station, hospital, sewers, laboratory, clock_tower) — le location usano solo playLocationAmbient()',
      '[AUDIO] BgmType ridotto da 10 a 4 tipi: title, combat, gameover, victory',
      '[AUDIO] Nuovo export resumeAmbient(): riprende l\'ambient sospeso quando si torna dal combat all\'esplorazione',
      '[AUDIO] Rimosso flag _customAmbientActive (dead code — non più controllato da playBgm)',
      '[AUDIO] page.tsx: rimosso locationBgmMap e tutti i riferimenti a currentLocationId — BGM effect ora gestisce solo fasi gioco, non location',
    ],
  },
  {
    version: '1.22.2',
    date: '2026-04-25',
    changes: [
      '[AUDIO] Sistema audio 100% DB-only — zero suoni hardcoded o sintetizzati, tutto caricabile dal pannello admin',
      '[AUDIO] Nuovo metodo playSfx(refKey): riproduce qualsiasi suono dal DB tramite refKey — usato per audio entity-specific e notifiche',
      '[AUDIO] BGM combat/gameover/victory sono caricati da DB tramite playBgm() — nessun fallback hardcoded',
      '[ADMIN] Sezione "Audio Combattimento" aggiunta in Impostazioni con upload per bgm_combat, bgm_gameover, bgm_victory',
      '[ADMIN] Ogni suono è caricabile dalla sua sezione: nemici (attacco/morte), abilità PG, abilità nemici, boss, location (ambient), notifiche, oggetti, eventi, missioni',
      '[UI] GameNotification: usa playSfx() con notif_sfx_{id} — se la notifica ha un suono caricato lo riproduce, altrimenti silenzio',
    ],
  },
];

/**
 * Get the latest version entry from history
 */
export function getLatestVersion() {
  return VERSION_HISTORY[VERSION_HISTORY.length - 1];
}

/**
 * Get formatted version string for display
 */
export function getVersionDisplay(): string {
  return `v${APP_VERSION}`;
}
