import type { TabId } from './tabGroups';

// ═══════════════════════════════════════════════════════════════
// Field Definitions
// ═══════════════════════════════════════════════════════════════
export interface FieldDef {
  key: string;
  label: string;
  type: 'text' | 'number' | 'boolean' | 'select' | 'textarea' | 'entity-search' | 'tag-editor' | 'entity-tag-editor' | 'item-pool' | 'text-list' | 'locked-locs' | 'sub-areas' | 'story-event' | 'status-apply' | 'status-cured' | 'quest-rewards' | 'event-choices' | 'rich-text-editor' | 'trade-inventory' | 'starting-items' | 'effects-editor' | 'item-box-defaults' | 'requirements-editor';
  options?: string[];
  enumGroup?: string; // key into ENUM_LABELS for Italian translations
  entitySearchEndpoint?: string; // for entity-search type
  entitySearchLabelKey?: string; // which field to show as label
  entityIconKey?: string; // optional icon field to show alongside labels
  placeholder?: string;
  required?: boolean;
  defaultValue?: string | number | boolean;
  colSpan?: number; // 1 or 2 for grid layout
  helpText?: string; // optional tooltip
}

export const FIELD_MAP: Record<TabId, FieldDef[]> = {
  items: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: pistol' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Pistola M1911' },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione oggetto', colSpan: 3 },
    { key: 'type', label: 'Tipo', type: 'select', options: ['weapon', 'healing', 'ammo', 'utility', 'antidote', 'bag', 'collectible', 'key', 'armor', 'accessory', 'weapon_mod'], enumGroup: 'itemType' },
    { key: 'rarity', label: 'Rarità', type: 'select', options: ['common', 'uncommon', 'rare', 'legendary'], enumGroup: 'rarity' },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 🔫' },
    { key: 'usable', label: 'Usabile', type: 'boolean', defaultValue: false },
    { key: 'equippable', label: 'Equipaggiabile', type: 'boolean', defaultValue: false },
    { key: 'stackable', label: 'Impilabile', type: 'boolean', defaultValue: true },
    { key: 'unico', label: 'Unico', type: 'boolean', defaultValue: false },
    { key: 'maxStack', label: 'Stack Max', type: 'number', defaultValue: 99 },
    // Weapon fields
    { key: 'weaponType', label: 'Tipo Arma', type: 'select', options: ['melee', 'ranged'], enumGroup: 'weaponType' },
    { key: 'ammoType', label: 'Tipo Munizione', type: 'entity-search', entitySearchEndpoint: '/api/admin/items?type=ammo', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'Cerca munizioni...' },
    // Equipment fields (armor/accessory/weapon_mod)
    { key: 'modType', label: 'Compatibilità Mod', type: 'select', options: ['melee', 'ranged', 'any'], enumGroup: 'modType', helpText: 'Weapon Mod: tipo arma compatibile' },
    { key: 'effects', label: '💡 Effetti Atomici', type: 'effects-editor', colSpan: 3, helpText: 'Stat bonus (on_equip): buff_stat flat, status_resist, status_chance_boost. Trigger combattimento: on_hit, on_turn_start, on_take_hit, on_use.' },
  ],
  quests: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: quest_marco_firstaid' },
    { key: 'npcId', label: 'NPC ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/npcs', entitySearchLabelKey: 'name', placeholder: 'es: npc_marco', required: true, colSpan: 2 },
    { key: 'name', label: 'Nome', type: 'text', required: true },
    { key: 'description', label: 'Descrizione', type: 'textarea', colSpan: 3 },
    { key: 'type', label: 'Tipo', type: 'select', options: ['fetch', 'kill', 'explore'], enumGroup: 'questType' },
    { key: 'targetId', label: 'Target ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/items', entitySearchLabelKey: 'name', placeholder: 'es: first_aid', required: true, colSpan: 2 },
    { key: 'targetCount', label: 'Target Count', type: 'number', defaultValue: 1 },
    { key: 'rewardItems', label: 'Ricompense', type: 'quest-rewards', colSpan: 3 },
    { key: 'rewardExp', label: 'EXP Ricompensa', type: 'number', defaultValue: 0 },
    { key: 'rewardDialogue', label: 'Dialogo Ricompensa', type: 'text-list', colSpan: 3 },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella lista missioni (non usato dal motore di gioco)' },
    { key: 'prerequisiteQuestId', label: 'Prerequisito Quest ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/quests', entitySearchLabelKey: 'name', placeholder: 'es: quest_prev', colSpan: 2 },
  ],
  events: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: event_blackout' },
    { key: 'title', label: 'Titolo', type: 'text', required: true },
    { key: 'description', label: 'Descrizione', type: 'textarea', colSpan: 3 },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 🌑' },
    { key: 'type', label: 'Tipo', type: 'select', options: ['blackout', 'alarm', 'collapse', 'lockdown', 'gas_leak', 'fire'], enumGroup: 'eventType' },
    { key: 'duration', label: 'Durata (turni)', type: 'number', defaultValue: 2 },
    { key: 'encounterRateMod', label: 'Mod. Incontri', type: 'number', defaultValue: 0 },
    { key: 'enemyStatMult', label: 'Molt. Nemici', type: 'number', defaultValue: 1.0 },
    { key: 'searchBonus', label: 'Bonus Ricerca', type: 'boolean', defaultValue: false },
    { key: 'damagePerTurn', label: 'Danni/Turno', type: 'number', defaultValue: 0 },
    { key: 'triggerChance', label: 'Prob. Trigger', type: 'number', defaultValue: 5 },
    { key: 'minTurn', label: 'Turno Minimo', type: 'number', defaultValue: 5 },
    { key: 'locationIds', label: 'Location IDs', type: 'entity-tag-editor', entitySearchEndpoint: '/api/admin/locations', entitySearchLabelKey: 'name', placeholder: 'Cerca e seleziona location...', colSpan: 3 },
    { key: 'onTriggerMessage', label: 'Msg Trigger', type: 'textarea', colSpan: 3 },
    { key: 'onEndMessage', label: 'Msg Fine', type: 'textarea', colSpan: 3 },
    { key: 'choices', label: 'Scelte', type: 'event-choices', colSpan: 3 },
  ],
  documents: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: doc_survivor_note' },
    { key: 'title', label: 'Titolo', type: 'text', required: true },
    { key: 'content', label: 'Contenuto', type: 'rich-text-editor', required: true, colSpan: 3 },
    { key: 'type', label: 'Tipo', type: 'select', options: ['diary', 'umbrella_file', 'note', 'photo', 'report', 'email'], enumGroup: 'documentType' },
    { key: 'locationId', label: 'Location ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/locations', entitySearchLabelKey: 'name', placeholder: 'es: city_outskirts', required: true, colSpan: 2 },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 📝' },
    { key: 'rarity', label: 'Rarità', type: 'select', options: ['common', 'uncommon', 'rare', 'legendary'], enumGroup: 'rarity', defaultValue: 'common' },
    { key: 'isSecret', label: 'Segreto', type: 'boolean', defaultValue: false },
    { key: 'hintRequired', label: 'Hint Richiesto', type: 'entity-search', entitySearchEndpoint: '/api/admin/documents', entitySearchLabelKey: 'title', placeholder: 'es: doc_chief_diary', helpText: 'Il giocatore deve aver trovato questo documento prima di poter trovare quello corrente', colSpan: 2 },
  ],
  sounds: [],
  images: [],
  notifications: [],
  npcs: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: npc_marco' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Marco' },
    { key: 'portrait', label: 'Emoji Ritratto', type: 'text', placeholder: 'es: 🔧' },
    { key: 'locationId', label: 'Location ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/locations', entitySearchLabelKey: 'name', placeholder: 'es: city_outskirts', required: true, colSpan: 2 },
    { key: 'greeting', label: 'Saluto', type: 'textarea', placeholder: 'Primo messaggio quando il giocatore incontra l\'NPC...', colSpan: 3 },
    { key: 'dialogues', label: 'Dialoghi', type: 'text-list', colSpan: 3 },
    { key: 'farewell', label: 'Saluto Finale', type: 'textarea', placeholder: 'Messaggio quando il giocatore chiude la conversazione...', colSpan: 3 },
    { key: 'questId', label: 'Quest ID', type: 'entity-search', entitySearchEndpoint: '/api/admin/quests', entitySearchLabelKey: 'name', placeholder: 'es: quest_marco_firstaid', helpText: 'La missione che questo NPC assegna al giocatore', colSpan: 2 },
    { key: 'tradeInventory', label: 'Inventario Scambi', type: 'trade-inventory', colSpan: 3 },
    { key: 'questCompletedDialogue', label: 'Dialogo Post-Quest', type: 'text-list', colSpan: 3 },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella mappa e nella lista NPC (non usato dal motore di gioco)' },
  ],
  characters: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: tank, healer, dps, control' },
    { key: 'archetype', label: 'Archetipo', type: 'select', options: ['tank', 'healer', 'dps', 'control', 'custom'], enumGroup: 'archetype' },
    { key: 'name', label: 'Nome Ruolo', type: 'text', required: true, placeholder: 'es: Tank, Medico, DPS, Controllo' },
    { key: 'displayName', label: 'Nome Personaggio', type: 'text', required: true, placeholder: 'es: Viktor Stahl, Maren Voss' },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione del personaggio...', colSpan: 3 },
    { key: 'maxHp', label: 'HP Massimo', type: 'number', defaultValue: 100 },
    { key: 'atk', label: 'ATK', type: 'number', defaultValue: 10 },
    { key: 'def', label: 'DEF', type: 'number', defaultValue: 10 },
    { key: 'spd', label: 'SPD', type: 'number', defaultValue: 10 },
    { key: 'specialName', label: 'Abilità PG 1', type: 'entity-search', entitySearchEndpoint: '/api/admin/specials', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: Barricata', colSpan: 2 },
    { key: 'special2Name', label: 'Abilità PG 2', type: 'entity-search', entitySearchEndpoint: '/api/admin/specials', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: Immolazione', colSpan: 2 },
    { key: 'passiveDescription', label: 'Passiva', type: 'textarea', placeholder: 'Descrizione abilità passiva...', colSpan: 3 },
    { key: 'portraitEmoji', label: 'Emoji Ritratto', type: 'text', placeholder: 'es: 🛡️' },
    { key: 'startingItems', label: 'Oggetti Iniziali', type: 'starting-items', colSpan: 3, helpText: 'Oggetti che il personaggio ha all\'inizio del gioco. Ogni entry è un oggetto con itemId, quantity e opzionalmente isEquipped (per armi/armature/accessori).' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella schermata selezione personaggi (non usato dal motore di gioco)' },
  ],
  locations: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: city_outskirts' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Periferia della Città' },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione della location', colSpan: 3 },
    { key: 'encounterRate', label: 'Prob. Incontri %', type: 'number', defaultValue: 0, helpText: 'Probabilità (0-100) di incontro nemico per azione' },
    { key: 'searchChance', label: 'Prob. Ricerca %', type: 'number', placeholder: '60 (default)', helpText: 'Probabilità base (0-100) di trovare qualcosa. Default: 60% se vuoto.' },
    { key: 'docChance', label: 'Prob. Documento %', type: 'number', placeholder: '35 (default)', helpText: 'Probabilità (0-100) di trovare un documento quando la ricerca ha successo. Default: 35% se vuoto. Documento e oggetti sono mutualmente esclusivi.' },
    { key: 'searchMax', label: 'Max Ricerche', type: 'number', placeholder: 'Random 1-3', helpText: 'Max ricerche per location. Vuoto = random 1-3, 0 = illimitate, N = max N ricerche.' },
    { key: 'isBossArea', label: 'Area Boss', type: 'boolean', defaultValue: false },
    { key: 'bossId', label: 'Boss', type: 'entity-search', entitySearchEndpoint: '/api/admin/enemies', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: nemesis, tyrant', colSpan: 2 },
    { key: 'enemyPool', label: 'Pool Nemici', type: 'entity-tag-editor', entitySearchEndpoint: '/api/admin/enemies', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'Cerca e seleziona nemici...', colSpan: 3 },
    { key: 'itemPool', label: 'Pool Oggetti', type: 'item-pool', colSpan: 3 },
    { key: 'nextLocations', label: 'Location Uscite', type: 'entity-tag-editor', entitySearchEndpoint: '/api/admin/locations', entitySearchLabelKey: 'name', placeholder: 'Cerca e seleziona location...', colSpan: 3 },
    { key: 'storyEvent', label: 'Evento Storia', type: 'story-event', colSpan: 3 },
    { key: 'ambientText', label: 'Testi Ambientali', type: 'text-list', colSpan: 3 },
    { key: 'lockedLocations', label: 'Location Bloccate', type: 'locked-locs', colSpan: 3 },
    { key: 'subAreas', label: 'Sotto-Aree', type: 'sub-areas', colSpan: 3 },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione (non usato dal motore di gioco)' },
  ],
  specials: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: colpo_mortale' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Colpo Mortale' },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 💀', colSpan: 2 },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione dell\'abilità...', colSpan: 3 },
    { key: 'category', label: 'Categoria', type: 'select', options: ['offensive', 'defensive', 'support', 'control'], enumGroup: 'specialCategory' },
    { key: 'targetType', label: 'Bersaglio', type: 'select', options: ['self', 'enemy', 'all_enemies', 'ally', 'all_allies'], enumGroup: 'specialTargetType' },
    { key: 'cooldown', label: 'Cooldown (turni)', type: 'number', defaultValue: 2, helpText: 'Turni di attesa prima di poter riutilizzare l\'abilità' },
    { key: 'effects', label: 'Effetti Atomici', type: 'effects-editor', colSpan: 3, helpText: 'Array di effetti atomici che compongono l\'abilità. Ogni effetto viene eseguito in ordine durante il combattimento.' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella lista abilità (non usato dal motore di gioco)' },
  ],
  enemies: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: zombie, zombie_dog' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Zombie' },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione del nemico...', colSpan: 3 },
    { key: 'maxHp', label: 'HP Massimo', type: 'number', defaultValue: 60 },
    { key: 'atk', label: 'ATK', type: 'number', defaultValue: 10 },
    { key: 'def', label: 'DEF', type: 'number', defaultValue: 5 },
    { key: 'spd', label: 'SPD', type: 'number', defaultValue: 5 },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 🧟' },
    { key: 'expReward', label: 'EXP Ricompensa', type: 'number', defaultValue: 15 },
    { key: 'lootTable', label: 'Tabella Loot', type: 'item-pool', colSpan: 3 },
    { key: 'abilities', label: 'Abilità', type: 'entity-tag-editor', entitySearchEndpoint: '/api/admin/enemy-abilities', entitySearchLabelKey: 'name', placeholder: 'Cerca e seleziona abilità nemiche...', colSpan: 3 },
    { key: 'isBoss', label: 'Boss', type: 'boolean', defaultValue: false },
    { key: 'variantGroup', label: 'Gruppo Variante', type: 'text', placeholder: 'es: zombie, licker, cerberus, hunter, tyrant, nemesis' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella lista nemici. Valori più alti = nemici mostrati dopo (progressione)' },
  ],
  'enemy-abilities': [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: morso, artigliata, carica_brutale' },
    { key: 'name', label: 'Nome Abilità', type: 'text', required: true, placeholder: 'es: Morso, Artigliata, Carica Brutale' },
    { key: 'description', label: 'Descrizione', type: 'textarea', placeholder: 'Descrizione dell\'attacco...', colSpan: 3 },
    { key: 'power', label: 'Potenza', type: 'number', defaultValue: 1.0, helpText: 'Moltiplicatore del danno (1.0 = normale, 2.0 = doppio)' },
    { key: 'chance', label: 'Prob. Uso %', type: 'number', defaultValue: 50, helpText: 'Probabilità che il nemico usi questa abilità (0-100)' },
    { key: 'effects', label: '💡 Effetti Atomici', type: 'effects-editor', colSpan: 3, helpText: 'Effetti atomici che compongono l\'abilità nemica. target "enemy" = party member, "self" = il nemico stesso, "all_enemies" = tutti i party members.' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella lista abilità nemiche' },
  ],
  'boss-phases': [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: tyrant_boss_phase_1' },
    { key: 'enemyId', label: 'Boss (Enemy ID)', type: 'entity-search', entitySearchEndpoint: '/api/admin/enemies', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: tyrant_boss, nemesis_boss', required: true, colSpan: 2 },
    { key: 'name', label: 'Nome Fase', type: 'text', required: true, placeholder: 'es: Terminus, Cortus, Pursuer' },
    { key: 'hpThreshold', label: 'Soglia HP %', type: 'number', defaultValue: 0.5, helpText: 'Percentuale HP (0.0-1.0) che attiva questa fase. Es: 0.3 = 30%' },
    { key: 'hpMultiplier', label: 'HP ×', type: 'number', defaultValue: 1.0, helpText: 'Moltiplicatore HP quando la fase si attiva' },
    { key: 'atkMultiplier', label: 'ATK ×', type: 'number', defaultValue: 1.0, helpText: 'Moltiplicatore ATK quando la fase si attiva' },
    { key: 'defMultiplier', label: 'DEF ×', type: 'number', defaultValue: 1.0, helpText: 'Moltiplicatore DEF quando la fase si attiva' },
    { key: 'spdMultiplier', label: 'SPD ×', type: 'number', defaultValue: 1.0, helpText: 'Moltiplicatore SPD quando la fase si attiva' },
    { key: 'newAbilities', label: 'Nuove Abilità', type: 'entity-tag-editor', entitySearchEndpoint: '/api/admin/enemy-abilities', entitySearchLabelKey: 'name', placeholder: 'Cerca e seleziona abilità nemiche da aggiungere...', colSpan: 3, helpText: 'Abilità che il boss guadagna quando questa fase si attiva' },
    { key: 'message', label: 'Messaggio Transizione', type: 'textarea', colSpan: 3, placeholder: '⚠️ Il Tyrant rivela i tentacoli! ENRAGE FASE 2!' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di attivazione (più basso = prima fase)' },
  ],
  'achievements': [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: first_blood, centurion' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Primo Sangue, Centurione' },
    { key: 'description', label: 'Descrizione', type: 'textarea', required: true, colSpan: 3, placeholder: 'es: Sconfiggi il tuo primo nemico.' },
    { key: 'icon', label: 'Icona', type: 'text', defaultValue: '🏆', placeholder: 'es: ⚔️, 💀, 🗺️' },
    { key: 'category', label: 'Categoria', type: 'select', required: true, options: ['combat', 'exploration', 'collection', 'story', 'special'], helpText: 'Categoria del traguardo' },
    { key: 'condition', label: 'Condizione', type: 'text', required: true, placeholder: 'es: first_kill, kill_100, visit_all_locations', helpText: 'Identificatore usato nel codice per verificare la condizione' },
    { key: 'hidden', label: 'Nascosto', type: 'boolean', defaultValue: false, helpText: 'Se true, nome e descrizione sono nascosti finché non sbloccato' },
    { key: 'reward', label: 'Ricompensa', type: 'text', placeholder: 'es: Coraggio: +5, Esp: +50', helpText: 'Testo descrittivo della ricompensa (solo flavor)' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0 },
  ],
  'endings': [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: ending_escape' },
    { key: 'title', label: 'Titolo', type: 'text', required: true, placeholder: 'es: Fuga Normale' },
    { key: 'subtitle', label: 'Sottotitolo', type: 'text', placeholder: 'es: Sopravvissuto... ma a quale prezzo?' },
    { key: 'description', label: 'Descrizione', type: 'textarea', colSpan: 3, placeholder: 'Descrizione narrativa del finale...' },
    { key: 'icon', label: 'Icona', type: 'text', defaultValue: '🏆', placeholder: 'es: 🏃, 💀, 🦸, 🔍' },
    { key: 'color', label: 'Colore', type: 'text', defaultValue: '#22c55e', placeholder: 'es: #22c55e, #ef4444', helpText: 'Colore hex per il tema del finale' },
    { key: 'requirements', label: '💡 Requisiti', type: 'requirements-editor', colSpan: 3, helpText: 'Condizioni necessarie per sbloccare questo finale' },
    { key: 'priority', label: 'Priorità', type: 'number', defaultValue: 0, helpText: 'Più alto = controllato prima. 1 = escape (default), 4 = truth (best)' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0 },
  ],
  'secret-rooms': [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: secret_rpd_evidence_room' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Stanza Prove Nascosta' },
    { key: 'description', label: 'Descrizione', type: 'textarea', colSpan: 3, placeholder: 'Descrizione narrativa della stanza segreta...' },
    { key: 'locationId', label: 'Location', type: 'entity-search', entitySearchEndpoint: '/api/admin/locations', entitySearchLabelKey: 'name', placeholder: 'es: rpd_station', required: true, colSpan: 2 },
    { key: 'discoveryMethod', label: 'Metodo Scoperta', type: 'select', options: ['search', 'document', 'npc_hint'], enumGroup: 'discoveryMethod' },
    { key: 'searchChance', label: 'Prob. Scoperta %', type: 'number', defaultValue: 15, helpText: 'Probabilità (0-100) di scoprire la stanza. Usato per "search" e "npc_hint". Per "document" è 50% fisso se il documento è posseduto.' },
    { key: 'requiredDocumentId', label: 'Documento Richiesto', type: 'entity-search', entitySearchEndpoint: '/api/admin/documents', entitySearchLabelKey: 'title', placeholder: 'es: doc_patient_record', helpText: 'Solo per metodo "document": documento necessario per scoprire la stanza', colSpan: 2 },
    { key: 'requiredNpcQuestId', label: 'Quest NPC Richiesta', type: 'entity-search', entitySearchEndpoint: '/api/admin/quests', entitySearchLabelKey: 'name', placeholder: 'es: quest_hannah_sewers', helpText: 'Solo per metodo "npc_hint": quest ID (non NPC ID) necessaria', colSpan: 2 },
    { key: 'hint', label: 'Suggerimento', type: 'textarea', placeholder: 'Testo del suggerimento mostrato al giocatore...', helpText: 'Mostrato come indizio nel log di gioco quando i requisiti sono quasi soddisfatti', colSpan: 3 },
    { key: 'lootTable', label: 'Loot Garantito', type: 'item-pool', colSpan: 3, helpText: 'Oggetti garantiti (usa chance 100 per essere sicuro). Tiro individuale per ogni entry.' },
    { key: 'uniqueItemId', label: 'Oggetto Unico', type: 'entity-search', entitySearchEndpoint: '/api/admin/items', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: lockpick, magnum, rocket_launcher', helpText: 'Oggetto unico garantito aggiunto al loot (opzionale)', colSpan: 2 },
    { key: 'uniqueItemQuantity', label: 'Quantità Unico', type: 'number', defaultValue: 1, helpText: 'Quantità dell\'oggetto unico' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0, helpText: 'Ordine di visualizzazione nella lista stanze segrete' },
  ],
  recipes: [
    { key: 'id', label: 'ID', type: 'text', required: true, placeholder: 'es: craft_pistol_ammo' },
    { key: 'name', label: 'Nome', type: 'text', required: true, placeholder: 'es: Munizioni Pistola' },
    { key: 'description', label: 'Descrizione', type: 'textarea', colSpan: 3, placeholder: 'Descrizione della ricetta...' },
    { key: 'icon', label: 'Icona', type: 'text', placeholder: 'es: 🔶' },
    { key: 'category', label: 'Categoria', type: 'select', options: ['ammo', 'healing', 'booster'], enumGroup: 'recipeCategory' },
    { key: 'ingredients', label: 'Ingredienti', type: 'item-box-defaults', colSpan: 3, helpText: 'Aggiungi gli ingredienti necessari per il craft. Ogni riga = un ingrediente con ID oggetto e quantità.' },
    { key: 'resultItemId', label: 'Risultato', type: 'entity-search', entitySearchEndpoint: '/api/admin/items', entitySearchLabelKey: 'name', entityIconKey: 'icon', placeholder: 'es: ammo_pistol', required: true, colSpan: 2, helpText: 'L\'oggetto che si ottiene dal craft' },
    { key: 'resultQty', label: 'Quantità Risultato', type: 'number', defaultValue: 1 },
    { key: 'difficulty', label: 'Difficoltà', type: 'select', options: ['easy', 'medium', 'hard'], enumGroup: 'craftDifficulty' },
    { key: 'sortOrder', label: 'Ordine', type: 'number', defaultValue: 0 },
  ],
  'avatars': [],
  'start-screen': [],
  settings:     [],
};
